Ext.define('B4.model.claimwork.FlattenedClaimWork', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'FlattenedClaimWork'
    },
    
    fields: [
        { name: 'Id' },
        { name: 'Num' },
        { name: 'Share' },
        { name: 'DebtorFullname' },
        { name: 'DebtorRoomAddress' },
        { name: 'DebtorRoomType' },
        { name: 'DebtorRoomNumber' },
        { name: 'DebtorDebtPeriod' },
        { name: 'DebtorDebtAmount' },
        { name: 'DebtorDutyAmount' },
        { name: 'DebtorDebtPaymentDate' },
        { name: 'DebtorDutyPaymentAssignment' },
        { name: 'DebtorClaimDeliveryDate' },
        { name: 'DebtorJurInstType' },
        { name: 'DebtorJurInstName' },
        { name: 'CourtClaimNum' },
        { name: 'CourtClaimDate' },
        { name: 'CourtClaimConsiderationResult' },
        { name: 'CourtClaimCancellationDate' },
        { name: 'CourtClaimRospName' },
        { name: 'CourtClaimRospDate' },
        { name: 'CourtClaimEnforcementProcNum' },
        { name: 'CourtClaimEnforcementProcDate' },
        { name: 'CourtClaimPaymentAssignmentNum' },
        { name: 'CourtClaimPaymentAssignmentDate' },
        { name: 'CourtClaimRospDebtExact' },
        { name: 'CourtClaimRospDutyExact' },
        { name: 'CourtClaimEnforcementProcActEndNum' },
        { name: 'CourtClaimDeterminationTurnDate' },
        { name: 'FkrRospName' },
        { name: 'FkrEnforcementProcDecisionNum' },
        { name: 'FkrEnforcementProcDate' },
        { name: 'FkrPaymentAssignementNum' },
        { name: 'FkrPaymentAssignmentDate' },
        { name: 'FkrDebtExact' },
        { name: 'FkrDutyExact' },
        { name: 'FkrEnforcementProcActEndNum' },
        { name: 'LawsuitCourtDeliveryDate' },
        { name: 'LawsuitDocNum' },
        { name: 'LawsuitConsiderationDate' },
       // { name: 'LawsuitConsiderationResult' },
        { name: 'LawsuitDebtExact' },
        { name: 'LawsuitDutyExact' },
        { name: 'ListListNum' },
        { name: 'ListListRopsDate' },
        { name: 'ListRospName' },
        { name: 'ListRospDate' },
        { name: 'ListEnfProcDecisionNum' },
        { name: 'ListEnfProcDate' },
        { name: 'ListPaymentAssignmentNum' },
        { name: 'ListPaymentAssignmentDate' },
        { name: 'ListRospDebtExacted' },
        { name: 'ListRospDutyExacted' },
        { name: 'ListEnfProcActEndNum' },
        { name: 'Archived' },
        { name: 'RloiId' },
        { name: 'ZVSPCourtDecision', defaultValue: 0 },
        { name: 'Note' },
        { name: 'ZVSPPenaltyAmmount' },
        { name: 'LawsuitDeterminationMotionless' },
        { name: 'LawsuitDeterminationMotionlessDate' },
        { name: 'LawsuitDeterminationReturn' },
        { name: 'LawsuitDeterminationReturnDate' },
        { name: 'LawsuitDeterminationJurDirected' },
        { name: 'LawsuitDeterminationJurDirectedDate' },
        { name: 'LawsuitDeterminationDenail' },
        { name: 'LawsuitDeterminationDenailDate' },
        //новые поля для Воронежа
        { name: 'LawsuitDocType' },
        { name: 'LawsuitDeterminationMotionFix' },
        { name: 'DebtorPenaltyAmount' },
        { name: 'LawsuitDistanceDecisionCancel' },
        { name: 'InstallmentPlan' },
        { name: 'LawsuitResultConsideration'}

            




    ]
});
