Ext.define('B4.model.actcheck.Action', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'ActCheckAction'
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'ActCheck' },
        { name: 'ActionType' },
        { name: 'Date' },
        { name: 'Number', defaultValue: null },
        { name: 'CreationPlace' },
        { name: 'StartDate', defaultValue: null },
        { name: 'StartTime', defaultValue: null },
        { name: 'EndDate', defaultValue: null },
        { name: 'EndTime', defaultValue: null },
        { name: 'ExecutionPlace', defaultValue: null },
        { name: 'ContrPersFio', defaultValue: null },
        { name: 'ContrPersBirthDate', defaultValue: null },
        { name: 'ContrPersBirthPlace', defaultValue: null },
        { name: 'ContrPersRegistrationAddress', defaultValue: null },
        { name: 'ContrPersLivingAddressMatched', defaultValue: null },
        { name: 'ContrPersLivingAddress', defaultValue: null },
        { name: 'ContrPersIsHirer', defaultValue: null },
        { name: 'ContrPersPhoneNumber', defaultValue: null },
        { name: 'ContrPersWorkPlace', defaultValue: null },
        { name: 'ContrPersPost', defaultValue: null },
        { name: 'IdentityDocType', defaultValue: null },
        { name: 'IdentityDocSeries', defaultValue: null },
        { name: 'IdentityDocNumber', defaultValue: null },
        { name: 'IdentityDocIssuedOn', defaultValue: null },
        { name: 'IdentityDocIssuedBy', defaultValue: null },
        { name: 'RepresentFio', defaultValue: null },
        { name: 'RepresentWorkPlace', defaultValue: null },
        { name: 'RepresentPost', defaultValue: null },
        { name: 'RepresentProcurationNumber', defaultValue: null },
        { name: 'RepresentProcurationIssuedOn', defaultValue: null },
        { name: 'RepresentProcurationValidPeriod', defaultValue: null },
        { name: 'PrototypeId' },
        { name: 'PrototypeActionType', defaultValue: null }
    ]
});