//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace Bars.GkhGji.Regions.Voronezh.Entities.SMEVPremises
{
    // 
    // Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/root/1.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/root/1.0.0", IsNullable = false)]
    public partial class MstrUnfitPremisesResponse
    {

        private Employee employeeField;

        private PremisesDetails premisesDetailsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0")]
        public Employee Employee
        {
            get
            {
                return this.employeeField;
            }
            set
            {
                this.employeeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0")]
        public PremisesDetails PremisesDetails
        {
            get
            {
                return this.premisesDetailsField;
            }
            set
            {
                this.premisesDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0", IsNullable = false)]
    public partial class Employee
    {

        private string employeeNameField;

        private string employeePostField;

        private string departmentField;

        /// <remarks/>
        public string EmployeeName
        {
            get
            {
                return this.employeeNameField;
            }
            set
            {
                this.employeeNameField = value;
            }
        }

        /// <remarks/>
        public string EmployeePost
        {
            get
            {
                return this.employeePostField;
            }
            set
            {
                this.employeePostField = value;
            }
        }

        /// <remarks/>
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0", IsNullable = false)]
    public partial class PremisesDetails
    {

        private string premisesInfoField;

        private PremisesDetailsPremisesAddress premisesAddressField;

        private string cadastralNumberField;

        private System.DateTime propertyRightsDateField;

        private PremisesDetailsDocumentRightsDetails documentRightsDetailsField;

        private string rightholderInfoField;

        private PremisesDetailsItem[] supervisionDetailsField;

        private PremisesDetailsInspectionDetails inspectionDetailsField;

        private PremisesDetailsConclusionDetails conclusionDetailsField;

        /// <remarks/>
        public string PremisesInfo
        {
            get
            {
                return this.premisesInfoField;
            }
            set
            {
                this.premisesInfoField = value;
            }
        }

        /// <remarks/>
        public PremisesDetailsPremisesAddress PremisesAddress
        {
            get
            {
                return this.premisesAddressField;
            }
            set
            {
                this.premisesAddressField = value;
            }
        }

        /// <remarks/>
        public string CadastralNumber
        {
            get
            {
                return this.cadastralNumberField;
            }
            set
            {
                this.cadastralNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime PropertyRightsDate
        {
            get
            {
                return this.propertyRightsDateField;
            }
            set
            {
                this.propertyRightsDateField = value;
            }
        }

        /// <remarks/>
        public PremisesDetailsDocumentRightsDetails DocumentRightsDetails
        {
            get
            {
                return this.documentRightsDetailsField;
            }
            set
            {
                this.documentRightsDetailsField = value;
            }
        }

        /// <remarks/>
        public string RightholderInfo
        {
            get
            {
                return this.rightholderInfoField;
            }
            set
            {
                this.rightholderInfoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Item", IsNullable = false)]
        public PremisesDetailsItem[] SupervisionDetails
        {
            get
            {
                return this.supervisionDetailsField;
            }
            set
            {
                this.supervisionDetailsField = value;
            }
        }

        /// <remarks/>
        public PremisesDetailsInspectionDetails InspectionDetails
        {
            get
            {
                return this.inspectionDetailsField;
            }
            set
            {
                this.inspectionDetailsField = value;
            }
        }

        /// <remarks/>
        public PremisesDetailsConclusionDetails ConclusionDetails
        {
            get
            {
                return this.conclusionDetailsField;
            }
            set
            {
                this.conclusionDetailsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0")]
    public partial class PremisesDetailsPremisesAddress
    {

        private string regionField;

        private string districtField;

        private string cityField;

        private string localityField;

        private string streetField;

        private sbyte houseField;

        private sbyte housingField;

        private sbyte buildingField;

        private sbyte apartmentField;

        private int indexField;

        /// <remarks/>
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        /// <remarks/>
        public string District
        {
            get
            {
                return this.districtField;
            }
            set
            {
                this.districtField = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string Locality
        {
            get
            {
                return this.localityField;
            }
            set
            {
                this.localityField = value;
            }
        }

        /// <remarks/>
        public string Street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        public sbyte House
        {
            get
            {
                return this.houseField;
            }
            set
            {
                this.houseField = value;
            }
        }

        /// <remarks/>
        public sbyte Housing
        {
            get
            {
                return this.housingField;
            }
            set
            {
                this.housingField = value;
            }
        }

        /// <remarks/>
        public sbyte Building
        {
            get
            {
                return this.buildingField;
            }
            set
            {
                this.buildingField = value;
            }
        }

        /// <remarks/>
        public sbyte Apartment
        {
            get
            {
                return this.apartmentField;
            }
            set
            {
                this.apartmentField = value;
            }
        }

        /// <remarks/>
        public int Index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0")]
    public partial class PremisesDetailsDocumentRightsDetails
    {

        private string numberField;

        private System.DateTime dateField;

        /// <remarks/>
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0")]
    public partial class PremisesDetailsItem
    {

        private string numberField;

        private System.DateTime dateField;

        /// <remarks/>
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0")]
    public partial class PremisesDetailsInspectionDetails
    {

        private string numberField;

        private System.DateTime dateField;

        /// <remarks/>
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn://x-artefacts-mstr-regional-unfitPremises-ru/commons/1.0.0")]
    public partial class PremisesDetailsConclusionDetails
    {

        private string numberField;

        private System.DateTime dateField;

        /// <remarks/>
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }
}
