Ext.define('B4.model.smevownershipproperty.SMEVOwnershipProperty', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'SMEVOwnershipProperty'
    },
    fields: [
        { name: 'ReqId'},
        { name: 'RequestDate'},
        { name: 'Inspector'},
        { name: 'RequestState' },
        { name: 'Answer' },
        { name: 'CalcDate' },
        { name: 'MessageId' },
        { name: 'RealityObject' },
        { name: 'Room' },
        { name: 'CadasterNumber' },
        { name: 'Municipality' },
        { name: 'QueryType' },
        { name: 'PublicPropertyLevel' },
        { name: 'AnswerFile' },
        { name: 'AttachmentFile' },
        { name: 'RegisterNumber' },
        { name: 'Value' },
        //gля из xml
        { name: 'Number' },
        { name: 'Date' },
        { name: 'Issuer' },
        { name: 'SignerFullName' },
        { name: 'SignerPosition' },
        { name: 'Type' },
        { name: 'RegNum' },
        { name: 'RegisterNumberDate' },
        { name: 'InitialCost' },
        { name: 'RegistrationNumber' },
        { name: 'Name' },
        { name: 'ORDocNum' },
        { name: 'ORDocDate' },
        { name: 'TDName' },
        { name: 'TDNum' },
        { name: 'TDDate' },
        { name: 'RDName' },
        { name: 'RDNum' },
        { name: 'RDDate' },
        { name: 'RhType' },
        { name: 'RhName' },
        { name: 'RhCNum' },
        { name: 'RhOGRN' },
        { name: 'RhOGRNDate' },
        { name: 'RhINN' },
        { name: 'RhSNILS' },
        { name: 'RhLastName' },
        { name: 'RhFirstName' },
        { name: 'RhMiddleName' },
        { name: 'RhPassSeries' },
        { name: 'RhPassNumber' },
        { name: 'RhPassIsBy' },
        { name: 'RhPassIsOn' },
        { name: 'OtherTypeOfCostName' },
        { name: 'CostOfOtherTypeOfLand' }
    ]
});