//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bars.GkhCr.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bars.GkhCr.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ActAuditDataExpense {
            get {
                object obj = ResourceManager.GetObject("ActAuditDataExpense", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ActuallyStartedWorksByHouses {
            get {
                object obj = ResourceManager.GetObject("ActuallyStartedWorksByHouses", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] AnalysOfRealizByProgram {
            get {
                object obj = ResourceManager.GetObject("AnalysOfRealizByProgram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ArchiveSmrReport {
            get {
                object obj = ResourceManager.GetObject("ArchiveSmrReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] BuildContractCr {
            get {
                object obj = ResourceManager.GetObject("BuildContractCr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] BuildContractCrToMailReportPSD {
            get {
                object obj = ResourceManager.GetObject("BuildContractCrToMailReportPSD", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] BuildContractCrToMailReportSMR {
            get {
                object obj = ResourceManager.GetObject("BuildContractCrToMailReportSMR", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] BuildContractsReestr {
            get {
                object obj = ResourceManager.GetObject("BuildContractsReestr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] BuilderRegister {
            get {
                object obj = ResourceManager.GetObject("BuilderRegister", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] BuildersInfo {
            get {
                object obj = ResourceManager.GetObject("BuildersInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ByProgramCrNew {
            get {
                object obj = ResourceManager.GetObject("ByProgramCrNew", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ComparePrograms {
            get {
                object obj = ResourceManager.GetObject("ComparePrograms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CompletionOfTheGraphicOnGivenDate {
            get {
                object obj = ResourceManager.GetObject("CompletionOfTheGraphicOnGivenDate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ContractObjectCrRegister {
            get {
                object obj = ResourceManager.GetObject("ContractObjectCrRegister", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CountPhoto {
            get {
                object obj = ResourceManager.GetObject("CountPhoto", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CountRealObjByBacklogWork {
            get {
                object obj = ResourceManager.GetObject("CountRealObjByBacklogWork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CountSumActAccepted {
            get {
                object obj = ResourceManager.GetObject("CountSumActAccepted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CountWorkCrReport {
            get {
                object obj = ResourceManager.GetObject("CountWorkCrReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CrAggregatedReport {
            get {
                object obj = ResourceManager.GetObject("CrAggregatedReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] CrWorkTypeSum {
            get {
                object obj = ResourceManager.GetObject("CrWorkTypeSum", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DataDevicesStatementReport {
            get {
                object obj = ResourceManager.GetObject("DataDevicesStatementReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DataStartedFinishedWorkReport {
            get {
                object obj = ResourceManager.GetObject("DataStartedFinishedWorkReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DetectRepeatingProgram {
            get {
                object obj = ResourceManager.GetObject("DetectRepeatingProgram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] DetectRepeatingProgramDistribServices {
            get {
                object obj = ResourceManager.GetObject("DetectRepeatingProgramDistribServices", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] EconomyByTypeWork {
            get {
                object obj = ResourceManager.GetObject("EconomyByTypeWork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] EconomyByTypeWorkToFund {
            get {
                object obj = ResourceManager.GetObject("EconomyByTypeWorkToFund", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ExtendedInformationAboutTransferFunds {
            get {
                object obj = ResourceManager.GetObject("ExtendedInformationAboutTransferFunds", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] FillingPassportControl {
            get {
                object obj = ResourceManager.GetObject("FillingPassportControl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Financing_Annex4_F4 {
            get {
                object obj = ResourceManager.GetObject("Financing_Annex4_F4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Financing_CheckRegister {
            get {
                object obj = ResourceManager.GetObject("Financing_CheckRegister", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] FinancingAnnex4F1 {
            get {
                object obj = ResourceManager.GetObject("FinancingAnnex4F1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] FKRToGZHIReport {
            get {
                object obj = ResourceManager.GetObject("FKRToGZHIReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] FormForMoscow3 {
            get {
                object obj = ResourceManager.GetObject("FormForMoscow3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] FulfilledWorkAmount {
            get {
                object obj = ResourceManager.GetObject("FulfilledWorkAmount", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] HomesWithoutGraphics {
            get {
                object obj = ResourceManager.GetObject("HomesWithoutGraphics", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] HousesCompletedWorkFact {
            get {
                object obj = ResourceManager.GetObject("HousesCompletedWorkFact", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] InfoActProtocolObjectCr {
            get {
                object obj = ResourceManager.GetObject("InfoActProtocolObjectCr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] InformationAboutContractors {
            get {
                object obj = ResourceManager.GetObject("InformationAboutContractors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] InformationByBuilders {
            get {
                object obj = ResourceManager.GetObject("InformationByBuilders", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] InformationOnObjectsCr {
            get {
                object obj = ResourceManager.GetObject("InformationOnObjectsCr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] InformOnHousesIncludedProgramCr {
            get {
                object obj = ResourceManager.GetObject("InformOnHousesIncludedProgramCr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] LaggingPerformanceOfWork {
            get {
                object obj = ResourceManager.GetObject("LaggingPerformanceOfWork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ListByManyApartmentsHouses {
            get {
                object obj = ResourceManager.GetObject("ListByManyApartmentsHouses", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] MkdByTypeRepairRegister {
            get {
                object obj = ResourceManager.GetObject("MkdByTypeRepairRegister", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NeedMaterials {
            get {
                object obj = ResourceManager.GetObject("NeedMaterials", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NeedMaterialsExtended {
            get {
                object obj = ResourceManager.GetObject("NeedMaterialsExtended", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] NormativeWorkersCount {
            get {
                object obj = ResourceManager.GetObject("NormativeWorkersCount", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ObjectCrInfo {
            get {
                object obj = ResourceManager.GetObject("ObjectCrInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ObjectCrInfoService {
            get {
                object obj = ResourceManager.GetObject("ObjectCrInfoService", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] OverhaulProposalReport {
            get {
                object obj = ResourceManager.GetObject("OverhaulProposalReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PhotoArchive {
            get {
                object obj = ResourceManager.GetObject("PhotoArchive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PlanedProgramIndicators {
            get {
                object obj = ResourceManager.GetObject("PlanedProgramIndicators", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] PlannedAllocationOfWorks {
            get {
                object obj = ResourceManager.GetObject("PlannedAllocationOfWorks", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ProgramCrInformationForFund {
            get {
                object obj = ResourceManager.GetObject("ProgramCrInformationForFund", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ProgramCrProgressOperativeReport {
            get {
                object obj = ResourceManager.GetObject("ProgramCrProgressOperativeReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ProgrammCrRealization {
            get {
                object obj = ResourceManager.GetObject("ProgrammCrRealization", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ProtocolsActsGjiReestr {
            get {
                object obj = ResourceManager.GetObject("ProtocolsActsGjiReestr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] QuartAndAnnualRepByFundExt {
            get {
                object obj = ResourceManager.GetObject("QuartAndAnnualRepByFundExt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RealObjByMonthlyCr {
            get {
                object obj = ResourceManager.GetObject("RealObjByMonthlyCr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RegisterMkdByTypeRepair {
            get {
                object obj = ResourceManager.GetObject("RegisterMkdByTypeRepair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RegisterMkdToBeRepaired {
            get {
                object obj = ResourceManager.GetObject("RegisterMkdToBeRepaired", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RegistryBySource {
            get {
                object obj = ResourceManager.GetObject("RegistryBySource", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] RepairProgressByKindOfWork {
            get {
                object obj = ResourceManager.GetObject("RepairProgressByKindOfWork", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] StaffingWorkers {
            get {
                object obj = ResourceManager.GetObject("StaffingWorkers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] StaffingWorkersByRealtyObjects {
            get {
                object obj = ResourceManager.GetObject("StaffingWorkersByRealtyObjects", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] StatusInformation {
            get {
                object obj = ResourceManager.GetObject("StatusInformation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] TatFormForMoscow3 {
            get {
                object obj = ResourceManager.GetObject("TatFormForMoscow3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] TatYearlyForFund {
            get {
                object obj = ResourceManager.GetObject("TatYearlyForFund", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] UploadingAtDataForFund {
            get {
                object obj = ResourceManager.GetObject("UploadingAtDataForFund", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WeeklyAboutCrProgress {
            get {
                object obj = ResourceManager.GetObject("WeeklyAboutCrProgress", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WorkKindsByMonitoringSmrReport {
            get {
                object obj = ResourceManager.GetObject("WorkKindsByMonitoringSmrReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WorkKindsCompareWithBaseProgram {
            get {
                object obj = ResourceManager.GetObject("WorkKindsCompareWithBaseProgram", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WorksGraphReport {
            get {
                object obj = ResourceManager.GetObject("WorksGraphReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WorksProgress {
            get {
                object obj = ResourceManager.GetObject("WorksProgress", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] YearlyForFund {
            get {
                object obj = ResourceManager.GetObject("YearlyForFund", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
