// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.3.0
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestFeaturesFilling
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.3.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("тесткейсы для добавления помещения к абоненту в разделе \"Реестр абонентов\"")]
    public partial class ТесткейсыДляДобавленияПомещенияКАбонентуВРазделеРеестрАбонентовFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "add_room_PersAccOwner.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "тесткейсы для добавления помещения к абоненту в разделе \"Реестр абонентов\"", "Региональный фонд - Абоненты - Реестр абонентов", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "region",
                        "place",
                        "street",
                        "houseNumber"});
            table1.AddRow(new string[] {
                        "kamchatka",
                        "Камчатский край, Алеутский р-н, с. Никольское",
                        "ул. 50 лет Октября",
                        "75"});
#line 6
testRunner.Given("добавлен жилой дом", ((string)(null)), table1, "Дано ");
#line 10
testRunner.And("у этого дома заполнено поле Вид дома \"Многоквартирный\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "RoomNum",
                        "Area",
                        "LivingArea",
                        "Type",
                        "OwnershipType"});
            table2.AddRow(new string[] {
                        "1",
                        "51",
                        "35",
                        "Жилое",
                        "Частная"});
#line 11
testRunner.And("у этого дома добавлено помещение", ((string)(null)), table2, "И ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Code",
                        "OkopfCode"});
            table3.AddRow(new string[] {
                        "тест",
                        "тест",
                        "тест"});
#line 15
testRunner.Given("добавлена организационно-правовая форма", ((string)(null)), table3, "Дано ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "OrganizationForm"});
            table4.AddRow(new string[] {
                        "111",
                        "тест"});
#line 19
testRunner.Given("добавлен контрагент c этой организационно-правовой формой", ((string)(null)), table4, "Дано ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "OwnerType",
                        "Surname",
                        "FirstName"});
            table5.AddRow(new string[] {
                        "Счет физ.лица",
                        "1",
                        "1"});
#line 23
testRunner.And("добавлен абонент с типом Счет физ.лица", ((string)(null)), table5, "И ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Contragent"});
            table6.AddRow(new string[] {
                        "111"});
#line 27
testRunner.And("добавлен абонент с типом Счет юр.лица", ((string)(null)), table6, "И ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("успешное добавление помещения к абоненту")]
        public virtual void УспешноеДобавлениеПомещенияКАбоненту()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("успешное добавление помещения к абоненту", ((string[])(null)));
#line 31
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 32
testRunner.Given("пользователь к этому абоненту добавляет запись по сведению о помещении с номером " +
                    "1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 33
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Дата открытия Л" +
                    "С \"01.01.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 34
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Жилой дом", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 35
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле № квартиры/поме" +
                    "щения", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 36
testRunner.And("у этого № квартиры/помещения заполняет поле Доля собственности \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 37
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 38
testRunner.Then("запись по этому сведению о помещении присутствует в сведениях о помещении по этом" +
                    "у абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("смена Даты открытия ЛС у помещения на абоненте")]
        public virtual void СменаДатыОткрытияЛСУПомещенияНаАбоненте()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("смена Даты открытия ЛС у помещения на абоненте", ((string[])(null)));
#line 40
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 41
testRunner.Given("пользователь к этому абоненту добавляет запись по сведению о помещении с номером " +
                    "1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 42
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Дата открытия Л" +
                    "С \"01.01.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 43
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Жилой дом", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 44
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле № квартиры/поме" +
                    "щения", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 45
testRunner.And("у этого № квартиры/помещения заполняет поле Доля собственности \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 46
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 47
testRunner.And("редактирует Дату открытия ЛС", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 48
testRunner.And("у этой записи по сведению о помещении заполняет поле Дата вступления значения в с" +
                    "илу \"01.02.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 49
testRunner.And("у этой записи по сведению о помещении заполняет поле Новое значение \"02.02.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 50
testRunner.Then("запись по этому сведению о помещении присутствует в сведениях о помещении по этом" +
                    "у абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 51
testRunner.And("у этой записи по этому сведению о помещении в Истории изменений добавляется запис" +
                    "ь", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 52
testRunner.And("у этой записи значение в поле Наименование параметра \"Дата открытия ЛС\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 53
testRunner.And("у этой записи значение в поле Описание измененного атрибута \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 54
testRunner.And("у этой записи значение в поле Значение \"02.02.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 55
testRunner.And("у этой записи значение в поле Дата начала действия значения \"01.02.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 56
testRunner.And("у этой записи значение в поле Дата установки значения = текущая дата", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 57
testRunner.And("у этой записи значение в поле Пользователь = текущий пользователь", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 58
testRunner.And("у этой записи значение в поле Файл \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("смена Доли собственности ЛС у помещения на абоненте")]
        public virtual void СменаДолиСобственностиЛСУПомещенияНаАбоненте()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("смена Доли собственности ЛС у помещения на абоненте", ((string[])(null)));
#line 60
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 61
testRunner.Given("пользователь к этому абоненту добавляет запись по сведению о помещении с номером " +
                    "1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 62
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Дата открытия Л" +
                    "С \"01.01.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 63
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Жилой дом", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 64
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле № квартиры/поме" +
                    "щения", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 65
testRunner.And("у этого № квартиры/помещения заполняет поле Доля собственности \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 66
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 67
testRunner.And("редактирует Долю собственности", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 68
testRunner.And("у этой записи по сведению о помещении заполняет поле Дата вступления значения в с" +
                    "илу \"01.02.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 69
testRunner.And("у этой записи по сведению о помещении заполняет поле Новое значение \"0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 70
testRunner.Then("запись по этому сведению о помещении присутствует в сведениях о помещении по этом" +
                    "у абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 71
testRunner.And("у этой записи по этому сведению о помещении в Истории изменений добавляется запис" +
                    "ь", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 72
testRunner.And("у этой записи значение в поле Наименование параметра \"Доля собственности\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 73
testRunner.And("у этой записи значение в поле Описание измененного атрибута \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 74
testRunner.And("у этой записи значение в поле Значение \"0\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 75
testRunner.And("у этой записи значение в поле Дата начала действия значения \"01.02.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 76
testRunner.And("у этой записи значение в поле Дата установки значения = текущая дата", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 77
testRunner.And("у этой записи значение в поле Пользователь = текущий пользователь", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 78
testRunner.And("у этой записи значение в поле Файл \"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("успешное добавление информации по договору к помещению на абоненте")]
        public virtual void УспешноеДобавлениеИнформацииПоДоговоруКПомещениюНаАбоненте()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("успешное добавление информации по договору к помещению на абоненте", ((string[])(null)));
#line 80
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 81
testRunner.Given("пользователь к этому абоненту добавляет запись по сведению о помещении с номером " +
                    "1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 82
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Дата открытия Л" +
                    "С \"01.01.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 83
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Жилой дом", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 84
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле № квартиры/поме" +
                    "щения", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 85
testRunner.And("у этого № квартиры/помещения заполняет поле Доля собственности \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 86
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 87
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Номер договора " +
                    "\"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 88
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Код/номер докум" +
                    "ента \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 89
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Тип документа о" +
                    " праве собственности \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 90
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Дата заключения" +
                    " договора \"01.01.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 91
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Дата выдачи док" +
                    "умента \"01.01.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 92
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Договор отправл" +
                    "ен \"01.01.2015\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 93
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 94
testRunner.Then("запись по этому сведению о помещении присутствует в сведениях о помещении по этом" +
                    "у абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
