// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.3.0
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestFeaturesFilling
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.3.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("тесткейсы граничных значений для добавления помещения к абоненту в разделе \"Реест" +
        "р абонентов\"")]
    public partial class ТесткейсыГраничныхЗначенийДляДобавленияПомещенияКАбонентуВРазделеРеестрАбонентовFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "add_room_PersAccOwner_boundaries.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "тесткейсы граничных значений для добавления помещения к абоненту в разделе \"Реест" +
                    "р абонентов\"", "Региональный фонд - Абоненты - Реестр абонентов", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "region",
                        "place",
                        "street",
                        "houseNumber"});
            table1.AddRow(new string[] {
                        "kamchatka",
                        "Камчатский край, Алеутский р-н, с. Никольское",
                        "ул. 50 лет Октября",
                        "75"});
#line 6
testRunner.Given("добавлен жилой дом", ((string)(null)), table1, "Дано ");
#line 10
testRunner.And("у этого дома заполнено поле Вид дома \"Многоквартирный\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "RoomNum",
                        "Area",
                        "LivingArea",
                        "Type",
                        "OwnershipType"});
            table2.AddRow(new string[] {
                        "1",
                        "51",
                        "35",
                        "Жилое",
                        "Частная"});
#line 11
testRunner.And("у этого дома добавлено помещение", ((string)(null)), table2, "И ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Code",
                        "OkopfCode"});
            table3.AddRow(new string[] {
                        "тест",
                        "тест",
                        "тест"});
#line 15
testRunner.Given("добавлена организационно-правовая форма", ((string)(null)), table3, "Дано ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "OrganizationForm"});
            table4.AddRow(new string[] {
                        "111",
                        "тест"});
#line 19
testRunner.Given("добавлен контрагент c этой организационно-правовой формой", ((string)(null)), table4, "Дано ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "OwnerType",
                        "Surname",
                        "FirstName"});
            table5.AddRow(new string[] {
                        "Счет физ.лица",
                        "1",
                        "1"});
#line 23
testRunner.And("добавлен абонент с типом Счет физ.лица", ((string)(null)), table5, "И ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Contragent"});
            table6.AddRow(new string[] {
                        "111"});
#line 27
testRunner.And("добавлен абонент с типом Счет юр.лица", ((string)(null)), table6, "И ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление помещения к абоненту при незаполненных обязательных полях")]
        public virtual void НеудачноеДобавлениеПомещенияКАбонентуПриНезаполненныхОбязательныхПолях()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление помещения к абоненту при незаполненных обязательных полях", ((string[])(null)));
#line 31
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 32
testRunner.Given("пользователь добавляет нового абонента", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 33
testRunner.And("пользователь у этого абонента заполняет поле Фамилия \"Оборин\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 34
testRunner.And("пользователь у этого абонента заполняет поле Имя \"Сергей\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 35
testRunner.When("пользователь сохраняет этого абонента", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 36
testRunner.And("пользователь добавляет запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 37
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 38
testRunner.Then("запись по этому сведению о помещении отсутствует в сведениях о помещении по этому" +
                    " абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 39
testRunner.And("падает ошибка с текстом \"Не заполнены обязательные поля: Жилой дом\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление помещения к абоненту без выбора квартиры")]
        public virtual void НеудачноеДобавлениеПомещенияКАбонентуБезВыбораКвартиры()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление помещения к абоненту без выбора квартиры", ((string[])(null)));
#line 41
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 42
testRunner.Given("пользователь добавляет нового абонента", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 43
testRunner.And("пользователь у этого абонента заполняет поле Фамилия \"Оборин\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 44
testRunner.And("пользователь у этого абонента заполняет поле Имя \"Сергей\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 45
testRunner.When("пользователь сохраняет этого абонента", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 46
testRunner.And("пользователь добавляет запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 47
testRunner.And("пользователь у этой записи по сведению о помещении заполняет поле Жилой дом", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 48
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 49
testRunner.Then("запись по этому сведению о помещении отсутствует в сведениях о помещении по этому" +
                    " абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 50
testRunner.And("падает ошибка с текстом \"Не заполнены обязательные поля: № квартиры/помещения\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("успешное изменение данных помещения при вводе граничных условий в 200 знаков, Ном" +
            "ер договора")]
        public virtual void УспешноеИзменениеДанныхПомещенияПриВводеГраничныхУсловийВ200ЗнаковНомерДоговора()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("успешное изменение данных помещения при вводе граничных условий в 200 знаков, Ном" +
                    "ер договора", ((string[])(null)));
#line 53
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 54
testRunner.Given("пользователь к этому абоненту добавляет запись по сведению о помещении с номером " +
                    "1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 55
testRunner.And("пользователь у этого помещения у абонента заполняет поле Номер договора 200 симво" +
                    "лов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 56
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 57
testRunner.Then("запись по этому сведению о помещении присутствует в сведениях о помещении по этом" +
                    "у абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное изменение данных помещения при вводе граничных условий в 201 знаков, Но" +
            "мер договора")]
        public virtual void НеудачноеИзменениеДанныхПомещенияПриВводеГраничныхУсловийВ201ЗнаковНомерДоговора()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное изменение данных помещения при вводе граничных условий в 201 знаков, Но" +
                    "мер договора", ((string[])(null)));
#line 60
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 61
testRunner.Given("пользователь к этому абоненту добавляет запись по сведению о помещении с номером " +
                    "1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 62
testRunner.And("пользователь у этого помещения у абонента заполняет поле Номер договора 201 симво" +
                    "лов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 63
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 64
testRunner.Then("запись по этому сведению о помещении отсутствует в сведениях о помещении по этому" +
                    " абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 65
testRunner.And("падает ошибка с текстом \"Не заполнены обязательные поля: Номер договора\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("успешное изменение данных помещения при вводе граничных условий в 200 знаков, Код" +
            "/номер документа")]
        public virtual void УспешноеИзменениеДанныхПомещенияПриВводеГраничныхУсловийВ200ЗнаковКодНомерДокумента()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("успешное изменение данных помещения при вводе граничных условий в 200 знаков, Код" +
                    "/номер документа", ((string[])(null)));
#line 68
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 69
testRunner.Given("пользователь к этому абоненту добавляет запись по сведению о помещении с номером " +
                    "1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 70
testRunner.And("пользователь у этого помещения у абонента заполняет поле Код/номер документа 200 " +
                    "символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 71
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 72
testRunner.Then("запись по этому сведению о помещении присутствует в сведениях о помещении по этом" +
                    "у абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное изменение данных помещения при вводе граничных условий в 201 знаков, Ко" +
            "д/номер документа")]
        public virtual void НеудачноеИзменениеДанныхПомещенияПриВводеГраничныхУсловийВ201ЗнаковКодНомерДокумента()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное изменение данных помещения при вводе граничных условий в 201 знаков, Ко" +
                    "д/номер документа", ((string[])(null)));
#line 75
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 76
testRunner.Given("пользователь к этому абоненту добавляет запись по сведению о помещении с номером " +
                    "1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 77
testRunner.And("пользователь у этого помещения у абонента заполняет поле Код/номер документа 201 " +
                    "символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 78
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 79
testRunner.Then("запись по этому сведению о помещении отсутствует в сведениях о помещении по этому" +
                    " абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 80
testRunner.And("падает ошибка с текстом \"Не заполнены обязательные поля: Код/номер документа\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("успешное изменение данных помещения при вводе граничных условий в 200 знаков, Тип" +
            " документа о праве собственности")]
        public virtual void УспешноеИзменениеДанныхПомещенияПриВводеГраничныхУсловийВ200ЗнаковТипДокументаОПравеСобственности()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("успешное изменение данных помещения при вводе граничных условий в 200 знаков, Тип" +
                    " документа о праве собственности", ((string[])(null)));
#line 83
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 84
testRunner.Given("пользователь к этому абоненту добавляет запись по сведению о помещении с номером " +
                    "1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 85
testRunner.And("пользователь у этого помещения у абонента заполняет поле Тип документа о праве со" +
                    "бственности 200 символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 86
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 87
testRunner.Then("запись по этому сведению о помещении присутствует в сведениях о помещении по этом" +
                    "у абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное изменение данных помещения при вводе граничных условий в 201 знаков, Ти" +
            "п документа о праве собственности")]
        public virtual void НеудачноеИзменениеДанныхПомещенияПриВводеГраничныхУсловийВ201ЗнаковТипДокументаОПравеСобственности()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное изменение данных помещения при вводе граничных условий в 201 знаков, Ти" +
                    "п документа о праве собственности", ((string[])(null)));
#line 90
this.ScenarioSetup(scenarioInfo);
#line 5
this.FeatureBackground();
#line 91
testRunner.Given("пользователь к этому абоненту добавляет запись по сведению о помещении с номером " +
                    "1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 92
testRunner.And("пользователь у этого помещения у абонента заполняет поле Тип документа о праве со" +
                    "бственности 201 символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 93
testRunner.When("пользователь сохраняет эту запись по сведению о помещении", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 94
testRunner.Then("запись по этому сведению о помещении отсутствует в сведениях о помещении по этому" +
                    " абоненту", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 95
testRunner.And("падает ошибка с текстом \"Не заполнены обязательные поля: Тип документа о праве со" +
                    "бственности\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
