// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.3.0
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestFeaturesFilling
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.3.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("тесткейсы граничных значений для справочника \"Организационно-правовые формы\"")]
    public partial class ТесткейсыГраничныхЗначенийДляСправочникаОрганизационно_ПравовыеФормыFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "organization_form_boundaries.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "тесткейсы граничных значений для справочника \"Организационно-правовые формы\"", "Справочники - Общие - Организационно-правовые формы", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("создание новой организационно-правовой формы с пустыми полями")]
        public virtual void СозданиеНовойОрганизационно_ПравовойФормыСПустымиПолями()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("создание новой организационно-правовой формы с пустыми полями", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
testRunner.Given("пользователь добавляет новую организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 8
testRunner.When("пользователь сохраняет эту организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 9
testRunner.Then("запись по этой форме присутствует в справочнике организационно-правовых форм", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное создание новой организационно-правовой формы при вводе граничных условий " +
            "в 300 знаков, Наименование")]
        public virtual void УдачноеСозданиеНовойОрганизационно_ПравовойФормыПриВводеГраничныхУсловийВ300ЗнаковНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное создание новой организационно-правовой формы при вводе граничных условий " +
                    "в 300 знаков, Наименование", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
testRunner.Given("пользователь добавляет новую организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 13
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Наименование 300" +
                    " символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 14
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код \"тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 15
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код ОКОПФ \"тест\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 16
testRunner.When("пользователь сохраняет эту организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 17
testRunner.Then("запись по этой форме присутствует в справочнике организационно-правовых форм", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное создание новой организационно-правовой формы при вводе граничных условий " +
            "в 301 знаков, Наименование")]
        public virtual void УдачноеСозданиеНовойОрганизационно_ПравовойФормыПриВводеГраничныхУсловийВ301ЗнаковНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное создание новой организационно-правовой формы при вводе граничных условий " +
                    "в 301 знаков, Наименование", ((string[])(null)));
#line 19
this.ScenarioSetup(scenarioInfo);
#line 20
testRunner.Given("пользователь добавляет новую организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 21
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Наименование 301" +
                    " символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 22
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код \"тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 23
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код ОКОПФ \"тест\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 24
testRunner.When("пользователь сохраняет эту организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 25
testRunner.Then("запись по этой форме отсутствует в справочнике организационно-правовых форм", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 26
testRunner.And("падает ошибка с текстом \"Количество знаков в поле Наименование не должно превышат" +
                    "ь 300 символов\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное создание новой организационно-правовой формы при вводе граничных условий " +
            "в 50 знаков, Код")]
        public virtual void УдачноеСозданиеНовойОрганизационно_ПравовойФормыПриВводеГраничныхУсловийВ50ЗнаковКод()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное создание новой организационно-правовой формы при вводе граничных условий " +
                    "в 50 знаков, Код", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
testRunner.Given("пользователь добавляет новую организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 32
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Наименование \"те" +
                    "ст\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 33
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код 50 символов " +
                    "\"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 34
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код ОКОПФ \"тест\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 35
testRunner.When("пользователь сохраняет эту организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 36
testRunner.Then("запись по этой форме присутствует в справочнике организационно-правовых форм", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное создание новой организационно-правовой формы при вводе граничных условий " +
            "в 51 знаков, Код")]
        public virtual void УдачноеСозданиеНовойОрганизационно_ПравовойФормыПриВводеГраничныхУсловийВ51ЗнаковКод()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное создание новой организационно-правовой формы при вводе граничных условий " +
                    "в 51 знаков, Код", ((string[])(null)));
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
testRunner.Given("пользователь добавляет новую организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 40
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Наименование \"те" +
                    "ст\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 41
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код 51 символов " +
                    "\"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 42
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код ОКОПФ \"тест\"" +
                    "", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 43
testRunner.When("пользователь сохраняет эту организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 44
testRunner.Then("запись по этой форме отсутствует в справочнике организационно-правовых форм", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 45
testRunner.And("падает ошибка с текстом \"Количество знаков в поле Код не должно превышать 50 симв" +
                    "олов\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное создание новой организационно-правовой формы при вводе граничных условий " +
            "в 50 знаков, Код ОКОПФ")]
        public virtual void УдачноеСозданиеНовойОрганизационно_ПравовойФормыПриВводеГраничныхУсловийВ50ЗнаковКодОКОПФ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное создание новой организационно-правовой формы при вводе граничных условий " +
                    "в 50 знаков, Код ОКОПФ", ((string[])(null)));
#line 49
this.ScenarioSetup(scenarioInfo);
#line 50
testRunner.Given("пользователь добавляет новую организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 51
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Наименование \"те" +
                    "ст\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 52
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код \"тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 53
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код ОКОПФ 50 сим" +
                    "волов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 54
testRunner.When("пользователь сохраняет эту организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 55
testRunner.Then("запись по этой форме присутствует в справочнике организационно-правовых форм", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное создание новой организационно-правовой формы при вводе граничных условий " +
            "в 51 знаков, Код ОКОПФ")]
        public virtual void УдачноеСозданиеНовойОрганизационно_ПравовойФормыПриВводеГраничныхУсловийВ51ЗнаковКодОКОПФ()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное создание новой организационно-правовой формы при вводе граничных условий " +
                    "в 51 знаков, Код ОКОПФ", ((string[])(null)));
#line 57
this.ScenarioSetup(scenarioInfo);
#line 58
testRunner.Given("пользователь добавляет новую организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 59
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Наименование \"те" +
                    "ст\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 60
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код \"тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 61
testRunner.And("пользователь у этой организационно-правовой формы заполняет поле Код ОКОПФ 51 сим" +
                    "волов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 62
testRunner.When("пользователь сохраняет эту организационно-правовую форму", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 63
testRunner.Then("запись по этой форме отсутствует в справочнике организационно-правовых форм", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 64
testRunner.And("падает ошибка с текстом \"Количество знаков в поле Код ОКОПФ не должно превышать 5" +
                    "0 символов\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
