// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.3.0
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18444
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestFeaturesFilling
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.3.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("тесткейсы граничных значений для справочника \"Отделы\"")]
    public partial class ТесткейсыГраничныхЗначенийДляСправочникаОтделыFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "zonal_inspection_boundaries.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "тесткейсы граничных значений для справочника \"Отделы\"", "Справочники - ГЖИ - Отделы", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление зональной жилищной инспекции при незаполненных обязательных " +
            "полях")]
        public virtual void НеудачноеДобавлениеЗональнойЖилищнойИнспекцииПриНезаполненныхОбязательныхПолях()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление зональной жилищной инспекции при незаполненных обязательных " +
                    "полях", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 8
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 9
testRunner.Then("запись по этой зональной жилищной инспекции не сохраняется и падает ошибка с текс" +
                    "том \"Не заполнены обязательные поля: Наименование\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное добавление зональной жилищной инспекции при вводе граничных условий в 300" +
            " знаков, Наименование")]
        public virtual void УдачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ300ЗнаковНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное добавление зональной жилищной инспекции при вводе граничных условий в 300" +
                    " знаков, Наименование", ((string[])(null)));
#line 11
this.ScenarioSetup(scenarioInfo);
#line 12
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 13
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Наименование 300 с" +
                    "имволов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 14
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 15
testRunner.Then("запись по этой зональной жилищной инспекции присутствует в справочнике зональных " +
                    "жилищных инспекций", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
            "01 знаков, Наименование")]
        public virtual void НеудачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ301ЗнаковНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
                    "01 знаков, Наименование", ((string[])(null)));
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 19
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Наименование 301 с" +
                    "имволов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 20
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 21
testRunner.Then("запись по этой зональной жилищной инспекции не сохраняется и падает ошибка с текс" +
                    "том \"Не заполнены обязательные поля: Наименование\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное добавление зональной жилищной инспекции при вводе граничных условий в 300" +
            " знаков, Зональное наименование")]
        public virtual void УдачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ300ЗнаковЗональноеНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное добавление зональной жилищной инспекции при вводе граничных условий в 300" +
                    " знаков, Зональное наименование", ((string[])(null)));
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 25
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Наименование \"зона" +
                    "льная жилищная инспекция тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 26
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Зональное наименов" +
                    "ание 300 символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 27
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 28
testRunner.Then("запись по этой зональной жилищной инспекции присутствует в справочнике зональных " +
                    "жилищных инспекций", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
            "01 знаков, Зональное наименование")]
        public virtual void НеудачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ301ЗнаковЗональноеНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
                    "01 знаков, Зональное наименование", ((string[])(null)));
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 32
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Наименование \"зона" +
                    "льная жилищная инспекция тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 33
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Зональное наименов" +
                    "ание 301 символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 34
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 35
testRunner.Then("запись по этой зональной жилищной инспекции не сохраняется и падает ошибка с текс" +
                    "том \"Не заполнены обязательные поля: Зональное наименование\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное добавление зональной жилищной инспекции при вводе граничных условий в 300" +
            " знаков, Наименование для бланка")]
        public virtual void УдачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ300ЗнаковНаименованиеДляБланка()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное добавление зональной жилищной инспекции при вводе граничных условий в 300" +
                    " знаков, Наименование для бланка", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line 38
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 39
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Наименование \"зона" +
                    "льная жилищная инспекция тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 40
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Наименование для б" +
                    "ланка 300 символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 41
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 42
testRunner.Then("запись по этой зональной жилищной инспекции присутствует в справочнике зональных " +
                    "жилищных инспекций", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
            "01 знаков, Наименование для бланка")]
        public virtual void НеудачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ301ЗнаковНаименованиеДляБланка()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
                    "01 знаков, Наименование для бланка", ((string[])(null)));
#line 44
this.ScenarioSetup(scenarioInfo);
#line 45
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 46
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Наименование \"зона" +
                    "льная жилищная инспекция тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 47
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Наименование для б" +
                    "ланка 301 символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 48
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 49
testRunner.Then("запись по этой зональной жилищной инспекции не сохраняется и падает ошибка с текс" +
                    "том \"Не заполнены обязательные поля: Наименование для бланка\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное добавление зональной жилищной инспекции при вводе граничных условий в 2 з" +
            "наков, Код отдела")]
        public virtual void УдачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ2ЗнаковКодОтдела()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное добавление зональной жилищной инспекции при вводе граничных условий в 2 з" +
                    "наков, Код отдела", ((string[])(null)));
#line 51
this.ScenarioSetup(scenarioInfo);
#line 52
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 53
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Наименование \"зона" +
                    "льная жилищная инспекция тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 54
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Код отдела 2 симво" +
                    "лов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 55
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 56
testRunner.Then("запись по этой зональной жилищной инспекции присутствует в справочнике зональных " +
                    "жилищных инспекций", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
            " знаков, Код отдела")]
        public virtual void НеудачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ3ЗнаковКодОтдела()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
                    " знаков, Код отдела", ((string[])(null)));
#line 58
this.ScenarioSetup(scenarioInfo);
#line 59
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 60
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Наименование \"зона" +
                    "льная жилищная инспекция тест\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 61
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Код отдела 3 симво" +
                    "лов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 62
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 63
testRunner.Then("запись по этой зональной жилищной инспекции не сохраняется и падает ошибка с текс" +
                    "том \"Не заполнены обязательные поля: Код отдела\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное добавление зональной жилищной инспекции при вводе граничных условий в 300" +
            " знаков, Адрес")]
        public virtual void УдачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ300ЗнаковАдрес()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное добавление зональной жилищной инспекции при вводе граничных условий в 300" +
                    " знаков, Адрес", ((string[])(null)));
#line 65
this.ScenarioSetup(scenarioInfo);
#line 66
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 67
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Адрес 300 символов" +
                    " \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 68
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 69
testRunner.Then("запись по этой зональной жилищной инспекции присутствует в справочнике зональных " +
                    "жилищных инспекций", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
            "01 знаков, Адрес")]
        public virtual void НеудачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ301ЗнаковАдрес()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
                    "01 знаков, Адрес", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line 72
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 73
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Адрес 301 символов" +
                    " \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 74
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 75
testRunner.Then("запись по этой зональной жилищной инспекции не сохраняется и падает ошибка с текс" +
                    "том \"Не заполнены обязательные поля: Адрес\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное добавление зональной жилищной инспекции при вводе граничных условий в 50 " +
            "знаков, E-mail")]
        public virtual void УдачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ50ЗнаковE_Mail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное добавление зональной жилищной инспекции при вводе граничных условий в 50 " +
                    "знаков, E-mail", ((string[])(null)));
#line 77
this.ScenarioSetup(scenarioInfo);
#line 78
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 79
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле E-mail 50 символов" +
                    " \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 80
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 81
testRunner.Then("запись по этой зональной жилищной инспекции присутствует в справочнике зональных " +
                    "жилищных инспекций", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 5" +
            "1 знаков, E-mail")]
        public virtual void НеудачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ51ЗнаковE_Mail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 5" +
                    "1 знаков, E-mail", ((string[])(null)));
#line 83
this.ScenarioSetup(scenarioInfo);
#line 84
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 85
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле E-mail 51 символов" +
                    " \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 86
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 87
testRunner.Then("запись по этой зональной жилищной инспекции не сохраняется и падает ошибка с текс" +
                    "том \"Не заполнены обязательные поля: E-mail\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное добавление зональной жилищной инспекции при вводе граничных условий в 50 " +
            "знаков, Телефон")]
        public virtual void УдачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ50ЗнаковТелефон()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное добавление зональной жилищной инспекции при вводе граничных условий в 50 " +
                    "знаков, Телефон", ((string[])(null)));
#line 89
this.ScenarioSetup(scenarioInfo);
#line 90
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 91
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Телефон 50 символо" +
                    "в \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 92
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 93
testRunner.Then("запись по этой зональной жилищной инспекции присутствует в справочнике зональных " +
                    "жилищных инспекций", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 5" +
            "1 знаков, Телефон")]
        public virtual void НеудачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ51ЗнаковТелефон()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 5" +
                    "1 знаков, Телефон", ((string[])(null)));
#line 95
this.ScenarioSetup(scenarioInfo);
#line 96
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 97
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле Телефон 51 символо" +
                    "в \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 98
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 99
testRunner.Then("запись по этой зональной жилищной инспекции не сохраняется и падает ошибка с текс" +
                    "том \"Не заполнены обязательные поля: Телефон\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное добавление зональной жилищной инспекции при вводе граничных условий в 30 " +
            "знаков, ОКАТО")]
        public virtual void УдачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ30ЗнаковОКАТО()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное добавление зональной жилищной инспекции при вводе граничных условий в 30 " +
                    "знаков, ОКАТО", ((string[])(null)));
#line 101
this.ScenarioSetup(scenarioInfo);
#line 102
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 103
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле ОКАТО 30 символов " +
                    "\"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 104
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 105
testRunner.Then("запись по этой зональной жилищной инспекции присутствует в справочнике зональных " +
                    "жилищных инспекций", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
            "1 знаков, ОКАТО")]
        public virtual void НеудачноеДобавлениеЗональнойЖилищнойИнспекцииПриВводеГраничныхУсловийВ31ЗнаковОКАТО()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное добавление зональной жилищной инспекции при вводе граничных условий в 3" +
                    "1 знаков, ОКАТО", ((string[])(null)));
#line 107
this.ScenarioSetup(scenarioInfo);
#line 108
testRunner.Given("пользователь добавляет новую зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 109
testRunner.And("пользователь у этой зональной жилищной инспекци заполняет поле ОКАТО 31 символов " +
                    "\"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 110
testRunner.When("пользователь сохраняет эту зональную жилищную инспекцию", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 111
testRunner.Then("запись по этой зональной жилищной инспекции не сохраняется и падает ошибка с текс" +
                    "том \"Не заполнены обязательные поля: ОКАТО\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
