<?xml version="1.0"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" version="2.0">
	<xsl:template match="/">
		<tns:Excerpt xmlns:tns="urn://ru.sgio.information-provision/1.0.0">
			<Number>1234567890</Number>
			<Date>1967-08-13</Date>
			<Issuer>String</Issuer>
			<IssuingDepartment>String</IssuingDepartment>
			<SignerFullName>String</SignerFullName>
			<SignerPosition>String</SignerPosition>
			<Type>Investment</Type>
			<RegisterNumber>String</RegisterNumber>
			<RegisterNumberDate>1967-08-13</RegisterNumberDate>
			<InitialCost>1000</InitialCost>
			<ResidualCost>1000</ResidualCost>
			<HasPartOfRights>true</HasPartOfRights>
			<ShareOfRight>
				<Share>String</Share>
				<Participant>
					<Name>String</Name>
					<OGRN>String</OGRN>
					<Share>String</Share>
				</Participant>
			</ShareOfRight>
			<CadasterNumber>
				<Number>String</Number>
				<NumberType>String</NumberType>
				<Date>2001-12-17T09:30:47Z</Date>
			</CadasterNumber>
			<Address>
				<Country>String</Country>
				<Region>String</Region>
				<District>String</District>
				<City>String</City>
				<Locality>String</Locality>
				<Street>String</Street>
				<ZipCode>String</ZipCode>
				<House>String</House>
				<Construct>String</Construct>
				<Build>String</Build>
				<Flat>String</Flat>
				<AddressFull>String</AddressFull>
			</Address>
			<OwnershipRight>
				<RegistrationNumber>String</RegistrationNumber>
				<RegistrationDate>1967-08-13</RegistrationDate>
				<Document>
					<Name>String</Name>
					<Number>String</Number>
					<Date>1967-08-13</Date>
				</Document>
			</OwnershipRight>
			<OtherRealRight>
				<Name>String</Name>
				<RegistrationNumber>String</RegistrationNumber>
				<RegistrationDate>1967-08-13</RegistrationDate>
				<Document>
					<Name>String</Name>
					<Number>String</Number>
					<Date>1967-08-13</Date>
				</Document>
			</OtherRealRight>
			<Charge>
				<PartName>String</PartName>
				<PartType>String</PartType>
				<Area>1000</Area>
				<Type>String</Type>
				<Number>String</Number>
				<Date>1967-08-13</Date>
				<Started>1967-08-13</Started>
				<Ended>1967-08-13</Ended>
				<Charger>
					<Type>FL</Type>
					<Name>String</Name>
					<CardNumber>String</CardNumber>
					<OGRN>String</OGRN>
					<OGRNDate>1967-08-13</OGRNDate>
					<INN>String</INN>
					<SNILS>String</SNILS>
					<LastName>String</LastName>
					<FirstName>String</FirstName>
					<MiddleName>String</MiddleName>
					<Passport>
						<Series>String</Series>
						<Number>String</Number>
						<IssuedBy>String</IssuedBy>
						<IssuedOn>1967-08-13</IssuedOn>
					</Passport>
				</Charger>
			</Charge>
			<RemovalFromTurnoverDocument>
				<Name>String</Name>
				<Number>String</Number>
				<Date>1967-08-13</Date>
			</RemovalFromTurnoverDocument>
			<TurnoverRestrictionDocument>
				<Name>String</Name>
				<Number>String</Number>
				<Date>1967-08-13</Date>
			</TurnoverRestrictionDocument>
			<Rightholder>
				<Type>UL</Type>
				<Name>String</Name>
				<CardNumber>String</CardNumber>
				<OGRN>String</OGRN>
				<OGRNDate>1967-08-13</OGRNDate>
				<INN>String</INN>
				<SNILS>String</SNILS>
				<LastName>String</LastName>
				<FirstName>String</FirstName>
				<MiddleName>String</MiddleName>
				<Passport>
					<Series>String</Series>
					<Number>String</Number>
					<IssuedBy>String</IssuedBy>
					<IssuedOn>1967-08-13</IssuedOn>
				</Passport>
				<Address>
					<Country>String</Country>
					<Region>String</Region>
					<District>String</District>
					<City>String</City>
					<Locality>String</Locality>
					<Street>String</Street>
					<ZipCode>String</ZipCode>
					<House>String</House>
					<Construct>String</Construct>
					<Build>String</Build>
					<Flat>String</Flat>
					<AddressFull>String</AddressFull>
				</Address>
			</Rightholder>
			<OtherCost>
				<OtherTypeOfCostName>String</OtherTypeOfCostName>
				<CostOfOtherTypeOfLand>1000</CostOfOtherTypeOfLand>
			</OtherCost>
			<Ship>
				<ShipType>String</ShipType>
				<Name>String</Name>
				<PurposeType>String</PurposeType>
				<Purpose>String</Purpose>
				<RegistrationNumber>String</RegistrationNumber>
				<RegistrationDate>1967-08-13</RegistrationDate>
				<ConstructionYear>String</ConstructionYear>
				<ConstructionPlace>String</ConstructionPlace>
				<Airport>String</Airport>
				<Harbor>String</Harbor>
				<InventoryNumber>String</InventoryNumber>
				<SerialNumber>String</SerialNumber>
			</Ship>
		</tns:Excerpt>
	</xsl:template>
</xsl:stylesheet>
