Ext.define('B4.model.smev.SMEVEGRUL', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'SMEVEGRUL'
    },
    fields: [
        { name: 'ReqId'},
        { name: 'RequestDate'},
        { name: 'Inspector'},
        { name: 'RequestState' },
        { name: 'INNReq' },
        { name: 'Answer' },
        { name: 'AddressRegOrg' },
        { name: 'AddressUL' },
        { name: 'CalcDate' },
        { name: 'AuthorizedCapitalAmmount' },
        { name: 'AuthorizedCapitalType'},
        { name: 'CodeRegOrg' },
        { name: 'CreateWayName' },
        { name: 'FIO' },
        { name: 'INN' },
        { name: 'KPP' },
        { name: 'Name' },
        { name: 'OGRN' },
        { name: 'OGRNDate' },
        { name: 'OKVEDCodes' },
        { name: 'OKVEDNames' },
        { name: 'OPFName' },
        { name: 'Pozition' },
        { name: 'RegOrgName' },
        { name: 'ResponceDate' },
        { name: 'ShortName' },
        { name: 'StateNameUL' },
        { name: 'TypePozitionName' },
        { name: 'MessageId' },
        { name: 'InnOgrn' },
        { name: 'CalcDate' },
    ]
});