namespace Bars.Gkh.Gis.Reports.SqlManager.ProxyClasses
{
    public class Report_10_61_1Proxy
    {
        public int nzp_graj { get; set; }
        public string point { get; set; }
        public string area { get; set; }
        public int cnt_doms { get; set; }
        public decimal tarif { get; set; }
        public int cnt_doms354pu { get; set; }
        public decimal rvaldlt { get; set; }
        public decimal nach_dpu { get; set; }
        public int cnt_doms354 { get; set; }
        public int cnt_ls_val354 { get; set; }
        public int cnt_pl_pu354 { get; set; }
        public decimal val_ipu354 { get; set; }
        public decimal sum_ipu354 { get; set; }
        public decimal r_ipud354 { get; set; }
        public decimal sum_ipud354 { get; set; }
        public int cnt_ls_norm354 { get; set; }
        public int cnt_pl_norm354 { get; set; }
        public decimal val_norm354 { get; set; }
        public decimal sum_norm354 { get; set; }
        public decimal r_normd354 { get; set; }
        public decimal sum_normd354 { get; set; }
        public decimal sum_ls354 { get; set; }
        public decimal r_ls354 { get; set; }
        public decimal nach_ls354 { get; set; }
        public int cnt_doms354b { get; set; }
        public int cnt_ls_val354b { get; set; }
        public int cnt_pl_pu354b { get; set; }
        public decimal val_ipu354b { get; set; }
        public decimal sum_ipu354b { get; set; }
        public decimal r_ipud354b { get; set; }
        public decimal sum_ipud354b { get; set; }
        public int cnt_ls_norm354b { get; set; }
        public int cnt_pl_norm354b { get; set; }
        public decimal val_norm354b { get; set; }
        public decimal sum_norm354b { get; set; }
        public decimal r_normd354b { get; set; }
        public decimal sum_normd354b { get; set; }
        public decimal sum_ls354b { get; set; }
        public decimal r_ls354b { get; set; }
        public decimal nach_ls354b { get; set; }
        public int cnt_doms354p { get; set; }
        public int cnt_ls_val354p { get; set; }
        public int cnt_pl_pu354p { get; set; }
        public decimal val_ipu354p { get; set; }
        public decimal sum_ipu354p { get; set; }
        public decimal r_ipud354p { get; set; }
        public decimal sum_ipud354p { get; set; }
        public int cnt_ls_norm354p { get; set; }
        public int cnt_pl_norm354p { get; set; }
        public decimal val_norm354p { get; set; }
        public decimal sum_norm354p { get; set; }
        public decimal r_normd354p { get; set; }
        public decimal sum_normd354p { get; set; }
        public decimal sum_ls354p { get; set; }
        public decimal sum_ls354odnp { get; set; }
        public decimal r_ls354p { get; set; }
        public decimal sum_ls354dltp { get; set; }
        public decimal sum_ls354dltsp { get; set; }
        public decimal rvaldlt344 { get; set; }
        public int cnt_doms354rt { get; set; }
        public int cnt_ls_val354rt { get; set; }
        public int cnt_pl_pu354rt { get; set; }
        public decimal val_ipu354rt { get; set; }
        public decimal sum_ipu354rt { get; set; }
        public decimal r_ipud354rt { get; set; }
        public decimal sum_ipud354rt { get; set; }
        public int cnt_ls_norm354rt { get; set; }
        public int cnt_pl_norm354rt { get; set; }
        public decimal val_norm354rt { get; set; }
        public decimal sum_norm354rt { get; set; }
        public decimal r_normd354rt { get; set; }
        public decimal sum_normd354rt { get; set; }
        public decimal sum_ls354rt { get; set; }
        public decimal r_ls354rt { get; set; }
        public decimal nach_ls354rt { get; set; }
        public int cnt_doms354n { get; set; }
        public int cnt_ls_val354n { get; set; }
        public int cnt_pl_pu354n { get; set; }
        public decimal val_ipu354n { get; set; }
        public decimal sum_ipu354n { get; set; }
        public decimal r_ipud354n { get; set; }
        public decimal sum_ipud354n { get; set; }
        public int cnt_ls_norm354n { get; set; }
        public int cnt_pl_norm354n { get; set; }
        public decimal val_norm354n { get; set; }
        public decimal sum_norm354n { get; set; }
        public decimal r_normd354n { get; set; }
        public decimal sum_normd354n { get; set; }
        public decimal sum_ls354n { get; set; }
        public decimal r_ls354n { get; set; }
        public decimal nach_ls354n { get; set; }
        public int year_ { get; set; }
        public int month_ { get; set; }
        public int nzp_serv { get; set; }
    }
}
