Ext.define('B4.model.Disposal', {
    extend: 'B4.model.DocumentGji',
    
    proxy: {
        type: 'b4proxy',
        controllerName: 'Disposal'
    },
    fields: [
        { name: 'Inspection', defaultValue: null },
        { name: 'IssuedDisposal', defaultValue: null },
        { name: 'ResponsibleExecution', defaultValue: null },
        { name: 'DateStart' },
        { name: 'DateEnd' },
        { name: 'TypeDisposal', defaultValue: 10 },
        { name: 'TypeAgreementProsecutor', defaultValue: 10 },
        { name: 'TypeAgreementResult', defaultValue: 10 },
        { name: 'KindCheck', defaultValue: null },
        { name: 'ActCheckGeneralId' },
        { name: 'ParentDocumentsList' },
        { name: 'TypeDocumentGji', defaultValue: 10 },
        { name: 'IsActCheckExist' },
        { name: 'RealityObjectCount' },
        { name: 'TypeSurveyNames' },
        { name: 'TypeBase' },
        { name: 'ContragentName' },
        { name: 'MunicipalityNames' },
        { name: 'InspectorNames' },
        { name: 'InspectionId', defaultValue: null },
        { name: 'InspectionType', defaultValue: null },
        { name: 'Description' },
        { name: 'ObjectVisitStart' },
        { name: 'ObjectVisitEnd' },
        { name: 'OutInspector', defaultValue: false },
        { name: 'HasChildrenActCheck', defaultValue: false },
        { name: 'HasActSurvey', defaultValue: false },
        { name: 'SendToErp' },
        { name: 'SendToErknm' },
        { name: 'ErpRegistrationNumber' },
        { name: 'ErknmRegistrationNumber' },
        { name: 'ErpId' },
        { name: 'ErknmId' },
        { name: 'ErpRegistrationDate' },
        { name: 'ErknmRegistrationDate' },
        { name: 'CountDays' },
        { name: 'CountHours' },
        { name: 'Prosecutor', defaultValue: null },
        { name: 'ReasonErpChecking' },
        { name: 'InspectionBase' },
        { name: 'NotificationType' },
        
        { name: 'TimeVisitStart' },
        { name: 'TimeVisitEnd' },
        { name: 'DocumentDateWithResultAgreement' },
        { name: 'DocumentNumberWithResultAgreement'},
        { name: 'NcNum' },
        { name: 'NcDate' },
        { name: 'NcNumLatter' },
        { name: 'NcDateLatter' },
        { name: 'NcObtained' },
        { name: 'NcSent' },
        { name: 'ControlType' },
        { name: 'LicenseNumber'},
        { name: 'TorId' },
        { name: 'PersonInspectionAddress' },
        { name: 'DocumentTime' },
        { name: 'InteractionPersonHour' },
        { name: 'InteractionPersonMinutes' },
        { name: 'SuspensionInspectionBase' },
        { name: 'SuspensionDateFrom' },
        { name: 'SuspensionDateTo' },
        { name: 'SuspensionTimeFrom' },
        { name: 'SuspensionTimeTo' }, 
        { name: 'InformationAboutHarm' }
    ]
});