Ext.define('B4.model.Resolution', {
    extend: 'B4.model.DocumentGji',
    idProperty: 'Id',

    proxy: {
        type: 'b4proxy',
        controllerName: 'Resolution'
    },
    fields: [
        { name: 'Inspection', defaultValue: null },
        { name: 'Executant', defaultValue: null },
        { name: 'Municipality', defaultValue: null },
        { name: 'Contragent', defaultValue: null },
        { name: 'Sanction', defaultValue: null },
        { name: 'Official', defaultValue: null },
        { name: 'PhysicalPerson' },
        { name: 'PhysicalPersonInfo' },
        { name: 'DeliveryDate' },
        { name: 'TypeInitiativeOrg', defaultValue: 10 },
        { name: 'SectorNumber' },
        { name: 'PenaltyAmount' },
        { name: 'ParentDocumentsList' },
        { name: 'TypeDocumentGji', defaultValue: 70 },
        { name: 'Paided', defaultValue: 30 },
        { name: 'DateTransferSsp' },
        { name: 'DocumentNumSsp' },
        { name: 'ContragentName' },
        { name: 'TypeExecutant' },
        { name: 'MunicipalityNames' },
        { name: 'DocumentDate' },
        { name: 'DateWriteOut' },
        { name: 'OfficialName' },
        { name: 'SumPays' },
        { name: 'DocumentTime', type: 'date', format: 'MS' },
        { name: 'InspectionId', defaultValue: null },
        { name: 'TypeBase', defaultValue: null },
        { name: 'TypeTerminationBasement', defaultValue: null },
        { name: 'GisUin' },
        { name: 'FineMunicipality' },
        { name: 'AbandonReason' },
        { name: 'ChangeReason' },
        { name: 'RoAddress' },
        { name: 'MoSettlement' },
        { name: 'Name' },
        { name: 'SurName' },
        { name: 'Patronymic' },
        { name: 'Citizenship' },
        { name: 'CitizenshipType', defaultValue: 10 },
        { name: 'SerialAndNumber' },
        { name: 'BirthDate' },
        { name: 'IssueDate' },
        { name: 'BirthPlace' },
        { name: 'IssuingAuthority' },
        { name: 'Company' },
        { name: 'RulingNumber' },
        { name: 'RulingDate' },
        { name: 'RulinFio' },
        { name: 'OffenderWas' },
        { name: 'Address'},
        { name: 'ProtocolMvdSerialAndNumber' },
        { name: 'ProtocolMvdBirthDate'},
        { name: 'ProtocolMvdIssueDate' },
        { name: 'ProtocolMvdBirthPlace' },
        { name: 'ProtocolMvdIssuingAuthority' },
        { name: 'ProtocolMvdCompany' },
        { name: 'ProtocolMvdId' },
        { name: 'ProtocolMvdPhysicalPersonInfo' },
        { name: 'ProtocolMvdPhysicalPerson' },
        { name: 'ProtocolMvdName' },
        { name: 'ProtocolMvdSurName' },
        { name: 'ProtocolMvdPatronymic' },
        { name: 'ProtocolMvdCitizenshipType', defaultValue: 10 },
        { name: 'ProtocolMvdCitizenship'},
        { name: 'ProtocolMvdCommentary' },
        { name: 'PatternDict' },
        { name: 'PersonInspectionAddress'},
        { name: 'SanctionsDuration'},
        { name: 'Snils'}
    ]
});