//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bars.GkhGji.Regions.Nnovgorod.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bars.GkhGji.Regions.Nnovgorod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdministrativeOffensesJurnalReport {
            get {
                object obj = ResourceManager.GetObject("AdministrativeOffensesJurnalReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AdministrativeOffensesResolution {
            get {
                object obj = ResourceManager.GetObject("AdministrativeOffensesResolution", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] AppealCitsJurnalAccounting {
            get {
                object obj = ResourceManager.GetObject("AppealCitsJurnalAccounting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_ActSurvey_5001 {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_ActSurvey_5001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_ActSurvey_5001_3 {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_ActSurvey_5001_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_ActSurvey_5001_all {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_ActSurvey_5001_all", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_ActSurvey_5002 {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_ActSurvey_5002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_ActSurvey_5002_all {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_ActSurvey_5002_all", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_ExecutiveDocPrescription_5001 {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_ExecutiveDocPrescription_5001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_ExecutiveDocPrescription_5003 {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_ExecutiveDocPrescription_5003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_Instruction_5001 {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_Instruction_5001", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_Instruction_5002 {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_Instruction_5002", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_Instruction_5003 {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_Instruction_5003", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_Instruction_5004_PP {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_Instruction_5004_PP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_Instruction_5005_PP {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_Instruction_5005_PP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BlockGJI_InstructionNotification {
            get {
                object obj = ResourceManager.GetObject("BlockGJI_InstructionNotification", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PrescriptionRegistrationJournal {
            get {
                object obj = ResourceManager.GetObject("PrescriptionRegistrationJournal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] RegistrationOutgoingDocuments {
            get {
                object obj = ResourceManager.GetObject("RegistrationOutgoingDocuments", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ScheduledInspectionSurveysJournal {
            get {
                object obj = ResourceManager.GetObject("ScheduledInspectionSurveysJournal", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
