// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Bars.Gkh.Qa.TestScenarios
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("тесткейсы граничных значений для раздела \"Заявления в суд\"")]
    [NUnit.Framework.CategoryAttribute("ScenarioInTransaction")]
    public partial class ТесткейсыГраничныхЗначенийДляРазделаЗаявленияВСудFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "petition_to_courtType_boundaries.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("ru-RU"), "тесткейсы граничных значений для раздела \"Заявления в суд\"", "Справочники - Претензионная и исковая работа - Заявления в суд", ProgrammingLanguage.CSharp, new string[] {
                        "ScenarioInTransaction"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("создание нового заявления в суд с пустыми полями, Код")]
        [NUnit.Framework.IgnoreAttribute()]
        public virtual void СозданиеНовогоЗаявленияВСудСПустымиПолямиКод()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("создание нового заявления в суд с пустыми полями, Код", new string[] {
                        "ignore"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given("пользователь добавляет новое заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 9
testRunner.And("пользователь у этого заявления в суд заполняет поле Краткое наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 10
testRunner.And("пользователь у этого заявления в суд заполняет поле Полное наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 11
testRunner.When("пользователь сохраняет этот заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 12
testRunner.Then("запись по этому заявлению в суд присутствует в справочнике заявлений в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("создание нового заявления в суд с пустыми полями, Краткое наименование")]
        public virtual void СозданиеНовогоЗаявленияВСудСПустымиПолямиКраткоеНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("создание нового заявления в суд с пустыми полями, Краткое наименование", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
testRunner.Given("пользователь добавляет новое заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 16
testRunner.And("пользователь у этого заявления в суд заполняет поле Код \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 17
testRunner.And("пользователь у этого заявления в суд заполняет поле Полное наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 18
testRunner.When("пользователь сохраняет этот заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 19
testRunner.Then("запись по этому заявлению в суд присутствует в справочнике заявлений в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("создание нового заявления в суд с пустыми полями, Полное наименование")]
        public virtual void СозданиеНовогоЗаявленияВСудСПустымиПолямиПолноеНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("создание нового заявления в суд с пустыми полями, Полное наименование", ((string[])(null)));
#line 21
this.ScenarioSetup(scenarioInfo);
#line 22
testRunner.Given("пользователь добавляет новое заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 23
testRunner.And("пользователь у этого заявления в суд заполняет поле Код \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 24
testRunner.And("пользователь у этого заявления в суд заполняет поле Краткое наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 25
testRunner.When("пользователь сохраняет этот заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 26
testRunner.Then("запись по этому заявлению в суд присутствует в справочнике заявлений в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное создание нового заявления в суд при вводе граничных условий в 100 знаков," +
            " Код")]
        public virtual void УдачноеСозданиеНовогоЗаявленияВСудПриВводеГраничныхУсловийВ100ЗнаковКод()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное создание нового заявления в суд при вводе граничных условий в 100 знаков," +
                    " Код", ((string[])(null)));
#line 28
this.ScenarioSetup(scenarioInfo);
#line 29
testRunner.Given("пользователь добавляет новое заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 30
testRunner.And("пользователь у этого заявления в суд заполняет поле Краткое наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 31
testRunner.And("пользователь у этого заявления в суд заполняет поле Полное наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 32
testRunner.And("пользователь у этого заявления в суд заполняет поле Код 100 символов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 33
testRunner.When("пользователь сохраняет этот заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 34
testRunner.Then("запись по этому заявлению в суд присутствует в справочнике заявлений в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное создание нового заявления в суд при вводе граничных условий в 101 знако" +
            "в, Код")]
        [NUnit.Framework.IgnoreAttribute()]
        public virtual void НеудачноеСозданиеНовогоЗаявленияВСудПриВводеГраничныхУсловийВ101ЗнаковКод()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное создание нового заявления в суд при вводе граничных условий в 101 знако" +
                    "в, Код", new string[] {
                        "ignore"});
#line 38
this.ScenarioSetup(scenarioInfo);
#line 39
testRunner.Given("пользователь добавляет новое заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 40
testRunner.And("пользователь у этого заявления в суд заполняет поле Краткое наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 41
testRunner.And("пользователь у этого заявления в суд заполняет поле Полное наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 42
testRunner.And("пользователь у этого заявления в суд заполняет поле Код 101 символов \"1\"\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 43
testRunner.When("пользователь сохраняет этот заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 44
testRunner.Then("запись по этому заявлению в суд отсутствует в справочнике заявлений в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 45
testRunner.And("падает ошибка с текстом \"Количество знаков в поле Код не должно превышать 100 сим" +
                    "волов\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное создание нового заявления в суд при вводе граничных условий в 500 знаков," +
            " Краткое наименование")]
        public virtual void УдачноеСозданиеНовогоЗаявленияВСудПриВводеГраничныхУсловийВ500ЗнаковКраткоеНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное создание нового заявления в суд при вводе граничных условий в 500 знаков," +
                    " Краткое наименование", ((string[])(null)));
#line 49
this.ScenarioSetup(scenarioInfo);
#line 50
testRunner.Given("пользователь добавляет новое заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 51
testRunner.And("пользователь у этого заявления в суд заполняет поле Код \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 52
testRunner.And("пользователь у этого заявления в суд заполняет поле Полное наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 53
testRunner.And("пользователь у этого заявления в суд заполняет поле Краткое наименование 500 симв" +
                    "олов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 54
testRunner.When("пользователь сохраняет этот заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 55
testRunner.Then("запись по этому заявлению в суд присутствует в справочнике заявлений в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное создание нового заявления в суд при вводе граничных условий в 501 знако" +
            "в, Краткое наименование")]
        [NUnit.Framework.IgnoreAttribute()]
        public virtual void НеудачноеСозданиеНовогоЗаявленияВСудПриВводеГраничныхУсловийВ501ЗнаковКраткоеНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное создание нового заявления в суд при вводе граничных условий в 501 знако" +
                    "в, Краткое наименование", new string[] {
                        "ignore"});
#line 59
this.ScenarioSetup(scenarioInfo);
#line 60
testRunner.Given("пользователь добавляет новое заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 61
testRunner.And("пользователь у этого заявления в суд заполняет поле Код \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 62
testRunner.And("пользователь у этого заявления в суд заполняет поле Полное наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 63
testRunner.And("пользователь у этого заявления в суд заполняет поле Краткое наименование 501 симв" +
                    "олов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 64
testRunner.When("пользователь сохраняет этот заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 65
testRunner.Then("запись по этому заявлению в суд отсутствует в справочнике заявлений в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 66
testRunner.And("падает ошибка с текстом \"Количество знаков в поле Краткое наименование не должно " +
                    "превышать 500 символов\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("удачное создание нового заявления в суд при вводе граничных условий в 3000 знаков" +
            ", Полное наименование")]
        public virtual void УдачноеСозданиеНовогоЗаявленияВСудПриВводеГраничныхУсловийВ3000ЗнаковПолноеНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("удачное создание нового заявления в суд при вводе граничных условий в 3000 знаков" +
                    ", Полное наименование", ((string[])(null)));
#line 70
this.ScenarioSetup(scenarioInfo);
#line 71
testRunner.Given("пользователь добавляет новое заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 72
testRunner.And("пользователь у этого заявления в суд заполняет поле Код \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 73
testRunner.And("пользователь у этого заявления в суд заполняет поле Краткое наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 74
testRunner.And("пользователь у этого заявления в суд заполняет поле Полное наименование 3000 симв" +
                    "олов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 75
testRunner.When("пользователь сохраняет этот заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 76
testRunner.Then("запись по этому заявлению в суд присутствует в справочнике заявлений в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("неудачное создание нового заявления в суд при вводе граничных условий в 3001 знак" +
            "ов, Полное наименование")]
        [NUnit.Framework.IgnoreAttribute()]
        public virtual void НеудачноеСозданиеНовогоЗаявленияВСудПриВводеГраничныхУсловийВ3001ЗнаковПолноеНаименование()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("неудачное создание нового заявления в суд при вводе граничных условий в 3001 знак" +
                    "ов, Полное наименование", new string[] {
                        "ignore"});
#line 80
this.ScenarioSetup(scenarioInfo);
#line 81
testRunner.Given("пользователь добавляет новое заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Дано ");
#line 82
testRunner.And("пользователь у этого заявления в суд заполняет поле Код \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 83
testRunner.And("пользователь у этого заявления в суд заполняет поле Краткое наименование \"тест1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 84
testRunner.And("пользователь у этого заявления в суд заполняет поле Полное наименование 3001 симв" +
                    "олов \"1\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line 85
testRunner.When("пользователь сохраняет этот заявление в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Когда ");
#line 86
testRunner.Then("запись по этому заявлению в суд отсутствует в справочнике заявлений в суд", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Тогда ");
#line 87
testRunner.And("падает ошибка с текстом \"Количество знаков в поле Полное наименование не должно п" +
                    "ревышать 3000 символов\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "И ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
