Ext.define('B4.model.manorg.contract.Base', {
    extend: 'B4.base.Model',
    requires: ['B4.enums.TypeContractManOrgRealObj'],
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'ManOrgBaseContract'
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'ManagingOrganization', defaultValue: null },
        { name: 'TypeContractManOrgRealObj', defaultValue: 10 },
        { name: 'DocumentName' },
        { name: 'DocumentNumber' },
        { name: 'DocumentDate' },
        { name: 'StartDate' },
        { name: 'EndDate' },
        { name: 'PlannedEndDate' },
        { name: 'Note' },
        { name: 'FileInfo', defaultValue: null },
        { name: 'HouseCount' },
        { name: 'IsTransferredManagement', defaultValue: 30 },
        { name: 'ManOrgTransferredManagement' },
        { name: 'Address' },
        { name: 'ManagingOrganizationName' },
        { name: 'TerminateReason' },
        { name: 'RealityObjectId' },
        { name: 'TypeContractString' },
        { name: 'ContractStopReason', defaultValue: 0 },
        { name: 'PaymentServicePeriodDate' },
        { name: 'IsLastDayPaymentServicePeriodDate' },
        { name: 'ThisMonthPaymentServiceDate', defaultValue: false },
        { name: 'ThisMonthInputMeteringDeviceValuesBeginDate', defaultValue: false },
        { name: 'ThisMonthInputMeteringDeviceValuesEndDate', defaultValue: false },
        { name: 'StartDatePaymentPeriod' },
        { name: 'EndDatePaymentPeriod' },
        { name: 'TerminateReason' },
        { name: 'TerminationDate' },
        { name: 'AreaMkd' },
        { name: 'AreaLivingNotLivingMkd' },
        { name: 'DateLicenceRegister' },
        { name: 'RegisterReason' },
        { name: 'DateLicenceDelete' },
        { name: 'DeleteReason' }
    ]
});