Ext.define('B4.model.person.QualificationCertificate', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'PersonQualificationCertificate'
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'Person', defaultValue: null },
        { name: 'Number' },
        { name: 'FullName' },
        { name: 'BlankNumber' },
        { name: 'IssuedDate' },
        { name: 'RecieveDate' },
        { name: 'EndDate' },
        { name: 'File' },
        { name: 'personId' },
        { name: 'HasDuplicate', defaultValue: false },
        { name: 'HasCancelled', defaultValue: false },
        { name: 'TypeCancelation', defaultValue: 0 },
        { name: 'CancelationDate' },
        { name: 'CancelNumber' },
        { name: 'CancelProtocolDate' },
        { name: 'CancelFile' },
        { name: 'HasRenewed', defaultValue: false },
        { name: 'CourtName' },
        { name: 'CourtActNumber' },
        { name: 'CourtActDate' },
        { name: 'ActFile' },
        { name: 'RequestToExam' },
        { name: 'RequestToExamName' },
        { name: 'FileIssueApplication' },
        { name: 'ApplicationDate' },
        { name: 'FileNotificationOfExamResults' },
        { name: 'IsFromAnotherRegion', defaultValue: false },
        { name: 'RegionCode' },
        { name: 'ProtocolDate' },
        { name: 'ProtocolNumber' },
        { name: 'DublicateIssuedDate' },
        { name: 'RenewIssuedDate' },
        { name: 'State' }
    ]
});