Ext.define('B4.model.smev.SMEVFNSLicRequest', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'SMEVFNSLicRequest'
    },
    fields: [
        { name: 'Id'},
        { name: 'Inspector'},
        { name: 'CalcDate'},
        { name: 'INN' },
        { name: 'NameUL' },
        { name: 'OGRN' },
        { name: 'FirstName' },
        { name: 'FamilyName' },
        { name: 'KindLic' },
        { name: 'DateLic' },
        { name: 'DateStartLic'},
        { name: 'DateEndLic' },
        { name: 'NumLic' },
        { name: 'SerLic' },
        { name: 'SLVDCode' },
        { name: 'VDName' },
        { name: 'PrAction' },
        { name: 'Address' },
        { name: 'PrActionAddress' },
        { name: 'DecisionKind' },
        { name: 'DecisionDateStart' },
        { name: 'DecisionDateEnd' },
        { name: 'DecisionDate' },
        { name: 'DecisionNum' },
        { name: 'DecisionOrgLic' },
        { name: 'LicOrgINN' },
        { name: 'LicOrgFullName' },
        { name: 'LicOrgShortName' },
        { name: 'LicOrgOGRN' },
        { name: 'LicOrgOKOGU' },
        { name: 'LicOrgRegion' },
        { name: 'Answer' },
        { name: 'FNSLicDecisionType', defaultValue: 0},
        { name: 'RequestState' },
        { name: 'FNSLicRequestType' },
        { name: 'MessageId' },
        { name: 'IdDoc' },
        { name: 'FNSLicPersonType' },
        { name: 'ManOrgLicense' },
        { name: 'DeleteIdDoc' }
    ]
});