Ext.define('B4.model.manorglicense.Request', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'ManOrgLicenseRequest'
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'Contragent' },
        { name: 'ContragentMunicipality' },
        { name: 'DateRequest' },
        { name: 'RegisterNumber' },
        { name: 'RegisterNum' },
        { name: 'ConfirmationOfDuty' },
        { name: 'ReasonOffers' },
        { name: 'File' },
        { name: 'ReasonRefusal' },
        { name: 'State' },
        { name: 'OfficialsCount', defaultValue: null },
        { name: 'Type', defaultValue: null },
        { name: 'Note' },
        { name: 'ManOrgLicense' },
        { name: 'Applicant' },
        { name: 'TaxSum'},
        { name: 'LicenseNum' },
        { name: 'LicenseState' },
        { name: 'ExtractLicenseNum' },
        { name: 'ExtractLicenseState' },
        { name: 'DateIssued' },
        { name: 'ProvDocFile' },
        { name: 'LicenseRegistrationReason' },
        { name: 'LicenseRejectReason' },
        { name: 'NoticeAcceptanceDate' },
        { name: 'NoticeViolationDate' },
        { name: 'ReviewDate' },
        { name: 'NoticeReturnDate' },
        { name: 'ReviewDateLk' },
        { name: 'PreparationOfferDate' },
        { name: 'SendResultDate' },
        { name: 'SendMethod' },
        { name: 'RevokeLicenseId' },
        { name: 'RevokeNumberLicense' },
        { name: 'RevokeStateLicense' },
        { name: 'OrderDate' },
        { name: 'OrderNumber' },
        { name: 'OrderFile' },
        { name: 'TypeIdentityDocument' },
        { name: 'IdSerial' },
        { name: 'IdNumber' },
        { name: 'IdIssuedBy' },
        { name: 'IdIssuedDate' }
    ]
});