Ext.define('B4.model.Fias', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'fias'
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'CodeRecord' },
        { name: 'TypeRecord', defaultValue:20 },
        { name: 'AOGuid' },
        { name: 'ParentGuid' },
        { name: 'AOId' },
        { name: 'PrevId' },
        { name: 'NextId' },
        { name: 'AOLevel', defaultValue: 1 },
        { name: 'Name' },
        { name: 'OffName' },
        { name: 'FormalName' },
        { name: 'ShortName' },
        { name: 'CodeRegion' },
        { name: 'CodeAuto' },
        { name: 'CodeArea' },
        { name: 'CodeCity' },
        { name: 'CodeCtar' },
        { name: 'CodePlace' },
        { name: 'CodeStreet' },
        { name: 'CodeExtr' },
        { name: 'CodeSext' },
        { name: 'PostalCode' },
        { name: 'IFNSFL' },
        { name: 'TerrIFNSFL' },
        { name: 'IFNSUL' },
        { name: 'TerrIFNSUL' },
        { name: 'OKATO' },
        { name: 'OKTMO' },
        { name: 'UpdateDate' },
        { name: 'KladrCode' },
        { name: 'KladrPlainCode' },
        { name: 'KladrCurrStatus' },
        { name: 'ActStatus', defaultValue: 1 },
        { name: 'CentStatus', defaultValue: 0 },
        { name: 'OperStatus', defaultValue: 1 },
        { name: 'StartDate' },
        { name: 'EndDate' },
        { name: 'ParentName' },
        { name: 'NormDoc' },
        { name: 'MirrorGuid' }
    ]
});