Ext.define('B4.model.Contragent', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    requires: ['B4.enums.ContragentState', 'B4.enums.GroundsTermination'],
    proxy: {
        type: 'b4proxy',
        controllerName: 'contragent'
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'Municipality', defaultValue: null },
        { name: 'Settlement', defaultValue: null },
        { name: 'Parent', defaultValue: null },
        { name: 'OrganizationForm', defaultValue: null },
        { name: 'OrganizationFormName' },
        { name: 'ContragentState', defaultValue: 10 },
        { name: 'AddressOutsideSubject' },
        { name: 'FactAddress' },
        { name: 'MailingAddress' },
        { name: 'JuridicalAddress' },
        { name: 'TrueJuridicalAddress' }, //TODO: Соместить с JuridicalAddress - см логику загрузки в ContragentViewModel
        { name: 'FiasOutsideSubjectAddress', defaultValue: null },
        { name: 'FiasFactAddress', defaultValue: null },
        { name: 'FiasMailingAddress', defaultValue: null },
        { name: 'FiasJuridicalAddress', defaultValue: null },
        { name: 'Name' },
        { name: 'ShortName' },
        { name: 'Inn' },
        { name: 'Kpp' },
        { name: 'IsEDSE' },
        { name: 'IsSOPR' },
        { name: 'Okved' }, 
        { name: 'Okpo' },
        { name: 'DateTermination' },
        { name: 'Description' },
        { name: 'Email' },
        { name: 'IsSite', defaultValue: false },
        { name: 'OfficialWebsite' },
        { name: 'Ogrn' },
        { name: 'OgrnRegistration' },
        { name: 'EgrulExcNumber' },
        { name: 'EgrulExcDate' },
        { name: 'OrgLegalForm' },
        { name: 'Phone' },
        { name: 'PhoneDispatchService' },
        { name: 'SubscriberBox' },
        { name: 'TweeterAccount' },
        { name: 'FrguRegNumber' },
        { name: 'FrguOrgNumber' },
        { name: 'FrguServiceNumber' },
        { name: 'YearRegistration' },
        { name: 'DateRegistration' },
        { name: 'ActivityDateStart' },
        { name: 'ActivityDateEnd' },
        { name: 'ActivityDescription' },
        { name: 'ActivityGroundsTermination', defaultValue: 10 },
        { name: 'TypeEntrepreneurship', defaultValue: 0 },
        { name: 'NameGenitive' },
        { name: 'NameDative' },
        { name: 'NameAccusative' },
        { name: 'NameAblative' },
        { name: 'NamePrepositional' },
        { name: 'Okato' },
        { name: 'Oktmo' },
        { name: 'TaxRegistrationSeries', defaultValue: null },
        { name: 'TaxRegistrationNumber', defaultValue: null },
        { name: 'TaxRegistrationIssuedBy', defaultValue: null },
        { name: 'TaxRegistrationDate', defaultValue: null },
        { name: 'RegDateInSocialUse' },
        { name: 'LicenseDateReceipt' },
        { name: 'Fax' },
        { name: 'ProviderCode', defaultValue: null },
        { name: 'TimeZoneType' },
        { name: 'Okogu' },
        { name: 'Okfs' },
        { name: 'MainRole' },
        { name: 'ReceiveNotifications'},
        { name: 'IncludeInSopr'}
    ]
});