Ext.define('B4.model.DateAreaOwner', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    
    proxy: {
        type: 'b4proxy',
        controllerName: 'DateAreaOwner'
    },
    fields: [
        { name: 'Id' },
        { name: 'ID_Object' },
        { name: 'CadastralNumber' },
        { name: 'ObjectType' },
        { name: 'ObjectTypeText' },
        { name: 'ObjectTypeName' },
        { name: 'AssignationCode' },
        { name: 'AssignationCodeText' },
        { name: 'Area' },
        { name: 'AreaText' },
        { name: 'AreaUnit' },
        { name: 'Floor' },
        { name: 'ID_Address' },
        { name: 'AddressContent' },
        { name: 'RegionCode' },
        { name: 'RegionName' },
        { name: 'OKATO' },
        { name: 'KLADR' },
        { name: 'CityName' },
        { name: 'StreetName' },
        { name: 'Level1Name' },
        { name: 'ApartmentName' },
        { name: 'ID_Subject' },
        { name: 'Code_SP' },
        { name: 'PersonContent' },
        { name: 'Surname' },
        { name: 'FirstName' },
        { name: 'Patronymic' },
        { name: 'DateBirth' },
        { name: 'Citizenship' },
        { name: 'Sex' },
        { name: 'PassportContent' },
        { name: 'TypeDocument' },
        { name: 'DocumentName' },
        { name: 'Series' },
        { name: 'Number' },
        { name: 'IssueDate' },
        { name: 'IssueOrgan' },
        //{ name: 'DeptCode' },
        { name: 'ID_AddressL' },
        { name: 'AddressContentL' },
        { name: 'RegionCodeL' },
        { name: 'RegionNameL' },
        { name: 'OKATOL' },
        { name: 'KLADRL' },
        { name: 'SNILS' },
        { name: 'ID_Record' },
        { name: 'RegNumber' },
        { name: 'Type' },
        { name: 'RegName' },
        { name: 'RegDate' },
        { name: 'RestorCourt' },
        { name: 'ShareText' },
        { name: 'IsProcessed' },
        { name: 'IsImported' },
        { name: 'IsProcessedWithCollision' }

    ]
});