Ext.define('B4.model.RosRegExtractPers', {
    extend: 'B4.base.Model',
    idProperty: 'Id',

    proxy: {
        type: 'b4proxy',
        controllerName: 'RosRegExtractPers'
    },
    fields: [
        { name: 'Id' },
        { name: 'Pers_Code_SP' },
        { name: 'Pers_Content' },
        { name: 'Pers_FIO_Surname' },
        { name: 'Pers_FIO_First' },
        { name: 'Pers_FIO_Patronymic' },
        { name: 'Pers_DateBirth' },
        { name: 'Pers_Place_Birth' },
        { name: 'Pers_Citizen' },
        { name: 'Pers_Sex' },
        { name: 'Pers_DocContent' },
        { name: 'Pers_DocType_Document' },
        { name: 'Pers_DocName' },
        { name: 'Pers_DocSeries' },
        { name: 'Pers_DocNumber' },
        { name: 'Pers_DocDate' },
        { name: 'Reg_ShareText' },        
        { name: 'Pers_Loc_ID_Address' },
        { name: 'Pers_Loc_Content' },
        { name: 'Pers_Loc_CountryCode' },
        { name: 'Pers_Loc_CountryName' },
        { name: 'Pers_Loc_RegionCode' },
        { name: 'Pers_Loc_RegionName' },
        { name: 'Pers_Loc_Code_OKATO' },
        { name: 'Pers_Loc_Code_KLADR' },
        { name: 'Pers_Loc_DistrictName' },
        { name: 'Pers_Loc_Urban_DistrictName' },
        { name: 'Pers_Loc_LocalityName' },
        { name: 'Pers_Loc_StreetName' },
        { name: 'Pers_Loc_Level1Name' },
        { name: 'Pers_Loc_Level2Name' },
        { name: 'Pers_Loc_Level3Name' },
        { name: 'Pers_Loc_ApartmentName' },
        { name: 'Pers_Loc_Other' },
        { name: 'Pers_Floc_ID_Address' },
        { name: 'Pers_Floc_Content' },
        { name: 'Pers_Floc_CountryCode' },
        { name: 'Pers_Floc_CountryName' },
        { name: 'Pers_Floc_RegionCode' },
        { name: 'Pers_Floc_RegionName' },
        { name: 'Pers_Floc_Code_OKATO' },
        { name: 'Pers_Floc_Code_KLADR' },
        { name: 'Pers_Floc_DistrictName' },
        { name: 'Pers_Floc_Urban_DistrictName' },
        { name: 'Pers_Floc_FlocalityName' },
        { name: 'Pers_Floc_StreetName' },
        { name: 'Pers_Floc_Level1Name' },
        { name: 'Pers_Floc_Level2Name' },
        { name: 'Pers_Floc_Level3Name' },
        { name: 'Pers_Floc_ApartmentName' },
        { name: 'Pers_Floc_Other' }
    ]
});