Ext.define('B4.model.DecisionGji', {
    extend: 'B4.model.DocumentGji',
    idProperty: 'Id',

    proxy: {
        type: 'b4proxy',
        controllerName: 'DecisionGji'
    },
    fields: [
        { name: 'Inspection', defaultValue: null },
        { name: 'IssuedDisposal', defaultValue: null },
        { name: 'ResponsibleExecution', defaultValue: null },
        { name: 'DateStart' },
        { name: 'DateEnd' },
        { name: 'TypeDisposal', defaultValue: 10 },
        { name: 'RiskCategory', defaultValue: 0 },
        { name: 'TypeAgreementProsecutor', defaultValue: 10 },
        { name: 'DocumentNumberWithResultAgreement'},
        { name: 'TypeAgreementResult', defaultValue: 10 },
        { name: 'DocumentDateWithResultAgreement' },
        { name: 'KindCheck', defaultValue: null },
        { name: 'ProsecutorOffice', defaultValue: null },
        { name: 'ActCheckGeneralId' },
        { name: 'ParentDocumentsList' },
        { name: 'TypeDocumentGji', defaultValue: 10 },
        { name: 'IsActCheckExist' },
        { name: 'RealityObjectCount' },
        { name: 'TypeSurveyNames' },
        { name: 'TypeBase' },
        { name: 'KindKNDGJI', defaultValue: 0 },
        { name: 'ContragentName' },
        { name: 'MunicipalityNames' },
        { name: 'InspectorNames' },
        { name: 'InspectionId', defaultValue: null },
        { name: 'InspectionType', defaultValue: null },
        { name: 'Description' },
        { name: 'ObjectVisitStart' },
        { name: 'ObjectVisitEnd' },
        { name: 'OutInspector', defaultValue: false },
        { name: 'HasChildrenActCheck', defaultValue: false },
        { name: 'HasActSurvey', defaultValue: false },
        { name: 'MoSettlement' },
        { name: 'PlaceName' },

        { name: 'ERPID' },
        { name: 'ERKNMID' },

        { name: 'HourOfProceedings' },
        { name: 'MinuteOfProceedings' },


        { name: 'TimeVisitStart' },
        { name: 'TimeVisitEnd' },
        { name: 'NcNum' },
        { name: 'NcDate' },
        { name: 'RequirNum' },
        { name: 'RequirDate' },
        { name: 'NcNumLatter' },
        { name: 'NcDateLatter' },
        { name: 'NcObtained' },
        { name: 'NcSent' },
        { name: 'Stage' },
        { name: 'ProcAprooveFile' },
        { name: 'ProcAprooveDate' },
        { name: 'FioProcAproove' },
        { name: 'PositionProcAproove' },
        { name: 'ProcAprooveNum' },

        { name: 'ProsecutorDecNumber' },
        { name: 'ProsecutorDecDate' },
        { name: 'DateStatement' },
        { name: 'TimeStatement' },
        { name: 'PeriodCorrect' }
    ]
});