Ext.define('B4.model.Resolution', {
    extend: 'B4.model.DocumentGji',
    idProperty: 'Id',

    proxy: {
        type: 'b4proxy',
        controllerName: 'Resolution'
    },
    fields: [
        { name: 'Inspection', defaultValue: null },
        { name: 'Executant', defaultValue: null },
        { name: 'Municipality', defaultValue: null },
        { name: 'Contragent', defaultValue: null },
        { name: 'Sanction', defaultValue: null },
        { name: 'Official', defaultValue: null },
        { name: 'Surname' },
        { name: 'FirstName' },
        { name: 'Patronymic' },
        { name: 'Position' },
        { name: 'PhysicalPerson' },
        { name: 'PhysicalPersonInfo' },
        { name: 'DeliveryDate' },
        { name: 'TypeInitiativeOrg', defaultValue: 10 },
        { name: 'SectorNumber' },
        { name: 'PenaltyAmount' },
        { name: 'ParentDocumentsList' },
        { name: 'TypeDocumentGji', defaultValue: 70 },
        { name: 'Paided', defaultValue: 30 },
        { name: 'PayStatus' },
        { name: 'ControlType' },
        { name: 'DateTransferSsp' },
        { name: 'DocumentNumSsp' },
        { name: 'ContragentName' },
        { name: 'TypeExecutant' },
        { name: 'Description' },       
        { name: 'ConcederationResult' },     
        { name: 'MunicipalityNames' },
        { name: 'DocumentDate' },
        { name: 'DateWriteOut' },
        { name: 'OfficialName' },
        { name: 'SumPays' },
        { name: 'DocumentTime', type: 'date', format: 'MS' },
        { name: 'InspectionId', defaultValue: null },
        { name: 'TypeBase', defaultValue: null },
        { name: 'TypeTerminationBasement', defaultValue: null },
        { name: 'GisUin' },
        { name: 'FineMunicipality' },
        { name: 'AbandonReason' },
        { name: 'RoAddress' },
        { name: 'MoSettlement' },
        { name: 'SerialAndNumber' },
        { name: 'BirthDate' },
        { name: 'IssueDate' },
        { name: 'BirthPlace' },
        { name: 'IssuingAuthority' },
        { name: 'Company' },
        { name: 'RulingNumber' },
        { name: 'RulingDate' },
        { name: 'RulinFio' },
        { name: 'OffenderWas' },
        { name: 'ProtocolMvdId' },
        { name: 'ProtocolMvdPhysicalPersonInfo' },
        { name: 'ProtocolMvdPhysicalPerson' },
        { name: 'Comment' },
        { name: 'ExecuteSSPNumber' },
        { name: 'DateEndExecuteSSP' },
        { name: 'DateExecuteSSP' },
        { name: 'DateOSPListArrive' },
        { name: 'OSPDecisionType' },
        { name: 'OSP' },
        { name: 'DateDeliverySsp' },
        // новые поля решения судебных участков
        { name: 'DecisionNumber' },
        { name: 'DecisionDate' },
        { name: 'DecisionEntryDate' },
        { name: 'Violation' },

        { name: 'InLawDate' },
        { name: 'DueDate' },
        { name: 'PaymentDate' },

        { name: 'TypePresence', defaultValue: 0 },
        { name: 'PersonRegistrationAddress' },
        { name: 'PersonFactAddress' },
        { name: 'Representative' },
        { name: 'ReasonTypeRequisites' },
        { name: 'PersonBirthDate' },
        { name: 'PersonBirthPlace' },

        { name: 'ViolatorFIO' },
        { name: 'ViolatorPosition' },

        { name: 'Payded50Percent', defaultValue: false },
        { name: 'WrittenOff', defaultValue: false },
        { name: 'WrittenOffComment'},

        { name: 'JudicalOffice' },
        { name: 'PhysicalPersonDocumentNumber' },
        { name: 'PhysicalPersonIsNotRF', defaultValue: false },
        { name: 'PhysicalPersonDocumentSerial' },
        { name: 'PhysicalPersonDocType' },
        { name: 'ArticleLaw' }
    ]
});