Ext.define('B4.model.ResolutionRospotrebnadzor', {
    extend: 'B4.model.DocumentGji',
    idProperty: 'Id',

    proxy: {
        type: 'b4proxy',
        controllerName: 'ResolutionRospotrebnadzor'
    },
    fields: [
        { name: 'Id'},
        { name: 'DocumentReason'},
        { name: 'DeliveryDate' },
        { name: 'GisUin' },
        { name: 'RevocationReason' },
        { name: 'TypeInitiativeOrg', defaultValue: 30 },
        { name: 'ExpireReason' },
        { name: 'PenaltyAmount' },
        { name: 'SspDocumentNum' },
        { name: 'Paided', defaultValue: 30 },
        { name: 'TransferToSspDate' },
        { name: 'PhysicalPerson' },
        { name: 'PhysicalPersonInfo' },
        { name: 'FineMunicipality', defaultValue: null },
        { name: 'Official', defaultValue: null },
        { name: 'LocationMunicipality', defaultValue: null },
        { name: 'Sanction', defaultValue: null },
        { name: 'Executant', defaultValue: null },
        { name: 'Contragent', defaultValue: null },
        // view
        { name: 'State', defaultValue: null },
        { name: 'SumPays', defaultValue: null },
        { name: 'RealityObjectIds', defaultValue: null },
        { name: 'MunicipalityNames', defaultValue: null },
        { name: 'MoNames', defaultValue: null },
        { name: 'MunicipalityId', defaultValue: null },
        { name: 'PlaceNames', defaultValue: null },
        { name: 'OfficialName', defaultValue: null },
        { name: 'OfficialId', defaultValue: null },
        { name: 'PenaltyAmount', defaultValue: null },
        { name: 'InspectionId', defaultValue: null },
        { name: 'TypeBase', defaultValue: null },
        { name: 'TypeDocumentGji', defaultValue: null },
        { name: 'TypeExecutant', defaultValue: null },
        { name: 'Sanction', defaultValue: null },
        { name: 'ContragentMuName', defaultValue: null },
        { name: 'ContragentMuId', defaultValue: null },
        { name: 'ContragentName', defaultValue: null },
        { name: 'DocumentDate', defaultValue: null },
        { name: 'DocumentNumber', defaultValue: null },
        { name: 'DocumentNum', defaultValue: null },
        { name: 'TypeDocumentGji', defaultValue: null },
        { name: 'RoAddress', defaultValue: null }
    ]
})