Ext.define('B4.model.GkuInfo', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'RealityObject',
        readAction: 'GetGkuInfo',
        timeout: 60000
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'Municipality'},
        { name: 'Address' },
        { name: 'Debt' },
        { name: 'Collection' },
        { name: 'FiasAddress' },
        { name: 'Address' },
        { name: 'FullAddress' },
        { name: 'CodeErc', defaultValue: null },
        { name: 'AreaLiving' },
        { name: 'AreaLivingOwned' },
        { name: 'AreaLivingNotLivingMkd' },
        { name: 'AreaMkd' },
        { name: 'IndividualAccountsCount' },
        { name: 'IndividualTenantAccountsCount' },
        { name: 'IndividualOwnerAccountsCount' },
        { name: 'LegalAccountsCount' },
        { name: 'LegalTenantAccountsCount' },
        { name: 'LegalOwnerAccountsCount' },
        { name: 'AreaBasement' },
        { name: 'DateLastOverhaul' },
        { name: 'DateCommissioning' },
        { name: 'CapitalGroup', defaultValue: null },
        { name: 'DateDemolition' },
        { name: 'MaximumFloors' },
        { name: 'RoofingMaterial', defaultValue: null },
        { name: 'WallMaterial', defaultValue: null },
        { name: 'IsInsuredObject', defaultValue: false },
        { name: 'Notation' },
        { name: 'SeriesHome' },
        { name: 'PhysicalWear' },
        { name: 'TypeOwnership', defaultValue: null },
        { name: 'Floors' },
        { name: 'FederalNum' },
        { name: 'NumberApartments' },
        { name: 'NumberEntrances' },
        { name: 'NumberLifts' },
        { name: 'NumberLiving' },
        { name: 'HavingBasement', defaultValue: 30 },
        { name: 'HeatingSystem', defaultValue: 20 },
        { name: 'ConditionHouse', defaultValue: 30 },
        { name: 'TypeHouse', defaultValue: 30 },
        { name: 'TypeRoof', defaultValue: 10 },
        { name: 'RoofingMaterialName' },
        { name: 'WallMaterialName' },
        { name: 'RoofingMaterialId' },
        { name: 'WallMaterialId' },
        { name: 'ManOrgNames' },
        { name: 'TypeContracts' },
        { name: 'WebCameraUrl' },
        { name: 'DateTechInspection' },
        { name: 'ResidentsEvicted', defaultValue: false },
        { name: 'TypeProject', defaultValue: false },
        { name: 'GkhCode' },
        { name: 'IsBuildSocialMortgage', defaultValue: 20 },
        { name: 'AreaOwned' },
        { name: 'AreaMunicipalOwned' },
        { name: 'AreaGovernmentOwned' },
        { name: 'AreaNotLivingFunctional' },
        { name: 'TotalBuildingVolume' },
        { name: 'CadastreNumber' },
        { name: 'FloorHeight' },
        { name: 'PrivatizationDateFirstApartment' },
        { name: 'BuildYear' },
        { name: 'State' },
        { name: 'PercentDebt' },
        { name: 'MonthCharge' },
        { name: 'Paid' },
        { name: 'NecessaryConductCr', defaultValue: 30 },
        { name: 'MethodFormFundCr', defaultValue: 0 },
        { name: 'HasJudgmentCommonProp', defaultValue: 20 },
        { name: 'IsRepairInadvisable', defaultValue: false }
    ]
});