Ext.define('B4.model.viewrosregextract.ViewRosRegExtractGov', {
    extend: 'B4.base.Model',
    idProperty: 'Id',

    proxy: {
        type: 'b4proxy',
        controllerName: 'ViewRosRegExtract'
    },
    fields: [
        { name: 'Id' },
        { name: 'gov_code_sp' },
        { name: 'gov_content' },
        { name: 'gov_name' },
        { name: 'gov_okato_code' },
        { name: 'gov_country' },
        { name: 'gov_address' },
        { name: 'rightnumber' },
        { name: 'reg_id_record' },
        { name: 'reg_regnumber' },
        { name: 'reg_type' },
        { name: 'reg_name' },
        { name: 'reg_regdate' },
        { name: 'reg_sharetext' },
        { name: 'desc_id_object' },
        { name: 'desc_cadastralnumber' },
        { name: 'desc_objecttype' },
        { name: 'desc_objecttypetext' },
        { name: 'desc_objecttypename' },
        { name: 'desc_assignationcode' },
        { name: 'desc_assignationcodetext' },
        { name: 'desc_area' },
        { name: 'desc_areatext' },
        { name: 'desc_areaunit' },
        { name: 'desc_floor' },
        { name: 'desc_id_address' },
        { name: 'desc_addresscontent' },
        { name: 'desc_regioncode' },
        { name: 'desc_regionname' },
        { name: 'desc_okato' },
        { name: 'desc_kladr' },
        { name: 'desc_cityname' },
        { name: 'desc_urban_district' },
        { name: 'desc_locality' },
        { name: 'desc_streetname' },
        { name: 'desc_level1name' },
        { name: 'desc_level2name' },
        { name: 'desc_apartmentname' }
    ]
});