Ext.define('B4.model.viewrosregextract.ViewRosRegExtractPers', {
    extend: 'B4.base.Model',
    idProperty: 'Id',

    proxy: {
        type: 'b4proxy',
        controllerName: 'ViewRosRegExtract'
    },
    fields: [
        { name: 'Id' },
        { name: 'pers_code_sp' },
        { name: 'pers_content' },
        { name: 'pers_fio_surname' },
        { name: 'pers_fio_first' },
        { name: 'pers_fio_patronymic' },
        { name: 'pers_datebirth' },
        { name: 'pers_place_birth' },
        { name: 'pers_citizen' },
        { name: 'pers_sex' },
        { name: 'pers_doccontent' },
        { name: 'pers_doctype_document' },
        { name: 'pers_docname' },
        { name: 'pers_docseries' },
        { name: 'pers_docnumber' },
        { name: 'pers_docdate' },
        { name: 'pers_loc_id_address' },
        { name: 'pers_loc_content' },
        { name: 'pers_loc_countrycode' },
        { name: 'pers_loc_countryname' },
        { name: 'pers_loc_regioncode' },
        { name: 'pers_loc_regionname' },
        { name: 'pers_loc_code_okato' },
        { name: 'pers_loc_code_kladr' },
        { name: 'pers_loc_districtname' },
        { name: 'pers_loc_urban_districtname' },
        { name: 'pers_loc_localityname' },
        { name: 'pers_loc_streetname' },
        { name: 'pers_loc_level1name' },
        { name: 'pers_loc_level2name' },
        { name: 'pers_loc_level3name' },
        { name: 'pers_loc_apartmentname' },
        { name: 'pers_loc_other' },
        { name: 'pers_floc_id_address' },
        { name: 'pers_floc_content' },
        { name: 'pers_floc_countrycode' },
        { name: 'pers_floc_countryname' },
        { name: 'pers_floc_regioncode' },
        { name: 'pers_floc_regionname' },
        { name: 'pers_floc_code_okato' },
        { name: 'pers_floc_code_kladr' },
        { name: 'pers_floc_districtname' },
        { name: 'pers_floc_urban_districtname' },
        { name: 'pers_floc_flocalityname' },
        { name: 'pers_floc_streetname' },
        { name: 'pers_floc_level1name' },
        { name: 'pers_floc_level2name' },
        { name: 'pers_floc_level3name' },
        { name: 'pers_floc_apartmentname' },
        { name: 'pers_floc_other' },
        { name: 'rightnumber' },
        { name: 'reg_id_record' },
        { name: 'reg_regnumber' },
        { name: 'reg_type' },
        { name: 'reg_name' },
        { name: 'reg_regdate' },
        { name: 'reg_sharetext' },
        { name: 'desc_id_object' },
        { name: 'desc_cadastralnumber' },
        { name: 'desc_objecttype' },
        { name: 'desc_objecttypetext' },
        { name: 'desc_objecttypename' },
        { name: 'desc_assignationcode' },
        { name: 'desc_assignationcodetext' },
        { name: 'desc_area' },
        { name: 'desc_areatext' },
        { name: 'desc_areaunit' },
        { name: 'desc_floor' },
        { name: 'desc_id_address' },
        { name: 'desc_addresscontent' },
        { name: 'desc_regioncode' },
        { name: 'desc_regionname' },
        { name: 'desc_okato' },
        { name: 'desc_kladr' },
        { name: 'desc_cityname' },
        { name: 'desc_urban_district' },
        { name: 'desc_locality' },
        { name: 'desc_streetname' },
        { name: 'desc_level1name' },
        { name: 'desc_level2name' },
        { name: 'desc_apartmentname' }
    ]
});