Ext.define('B4.model.viewrosregextract.ViewRosRegExtractOrg', {
    extend: 'B4.base.Model',
    idProperty: 'Id',

    proxy: {
        type: 'b4proxy',
        controllerName: 'ViewRosRegExtract'
    },
    fields: [
        { name: 'Id' },
        { name: 'org_code_sp' },
        { name: 'org_content' },
        { name: 'org_code_opf' },
        { name: 'org_name' },
        { name: 'org_inn' },
        { name: 'org_code_ogrn' },
        { name: 'org_regdate' },
        { name: 'org_agencyregistration' },
        { name: 'org_code_cpp' },
        { name: 'org_areaunit' },
        { name: 'org_loc_id_address' },
        { name: 'org_loc_content' },
        { name: 'org_loc_regioncode' },
        { name: 'org_loc_regionname' },
        { name: 'org_loc_code_okato' },
        { name: 'org_loc_code_kladr' },
        { name: 'org_loc_cityname' },
        { name: 'org_loc_streetname' },
        { name: 'org_loc_level1name' },
        { name: 'org_floc_id_address' },
        { name: 'org_floc_content' },
        { name: 'org_floc_regioncode' },
        { name: 'org_floc_regionname' },
        { name: 'org_floc_code_okato' },
        { name: 'org_floc_code_kladr' },
        { name: 'org_floc_cityname' },
        { name: 'org_floc_streetname' },
        { name: 'org_floc_level1name' },
        { name: 'rightnumber' },
        { name: 'reg_id_record' },
        { name: 'reg_regnumber' },
        { name: 'reg_type' },
        { name: 'reg_name' },
        { name: 'reg_regdate' },
        { name: 'reg_sharetext' },
        { name: 'desc_id_object' },
        { name: 'desc_cadastralnumber' },
        { name: 'desc_objecttype' },
        { name: 'desc_objecttypetext' },
        { name: 'desc_objecttypename' },
        { name: 'desc_assignationcode' },
        { name: 'desc_assignationcodetext' },
        { name: 'desc_area' },
        { name: 'desc_areatext' },
        { name: 'desc_areaunit' },
        { name: 'desc_floor' },
        { name: 'desc_id_address' },
        { name: 'desc_addresscontent' },
        { name: 'desc_regioncode' },
        { name: 'desc_regionname' },
        { name: 'desc_okato' },
        { name: 'desc_kladr' },
        { name: 'desc_cityname' },
        { name: 'desc_urban_district' },
        { name: 'desc_locality' },
        { name: 'desc_streetname' },
        { name: 'desc_level1name' },
        { name: 'desc_level2name' },
        { name: 'desc_apartmentname' }
    ]
});