Ext.define('B4.model.objectcr.TypeWorkCr', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'TypeWorkCr'
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'ObjectCr', defaultValue: null },
        { name: 'Work', defaultValue: null },
        { name: 'WorkName' },
        { name: 'TypeWork' },
        { name: 'UnitMeasureName' },
        { name: 'FinanceSource', defaultValue: null },
        { name: 'FinanceSourceName' },
        { name: 'HasPsd' },
        { name: 'IsEmergrncy' },
        { name: 'SumMaterialsRequirement' },
        { name: 'Sum' },
        { name: 'MaxCost' },
        { name: 'Description' },
        { name: 'DateStartWork' },
        { name: 'DateEndWork' },
        { name: 'VolumeOfCompletion' },
        { name: 'Volume' },
        { name: 'ManufacturerName' },
        { name: 'PercentOfCompletion' },
        { name: 'CostSum' },
        { name: 'StageWorkCr', defaultValue: null },
        { name: 'StageWorkCrName' },
        { name: 'CountWorker' },
        { name: 'WorkFinSourceName' },
        { name: 'AdditionalDate' },
        { name: 'ControlDate' },
        { name: 'IsActive', defaultValue: true },
        { name: 'IsDpkrCreated' },
        { name: 'YearRepair' },
        { name: 'Address' },
        { name: 'Municipality' },
        { name: 'CrFund' },
        { name: 'Specials' },
        { name: 'ProgramCr' },
        { name: 'RealityObject' },
        { name: 'State' },
        { name: 'DpkrSum' },
        { name: 'DpkrVolume' },
        { name: 'CalcBy' },
        { name: 'DpkrUnitMeasure' }
    ]
});