Ext.define('B4.model.ObjectCr', {
    extend: 'B4.base.Model',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'ObjectCr'
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'MonitoringSmrId', useNull: true },
        { name: 'MonitoringSmr', defaultValue: null },
        { name: 'RealityObject' },
        { name: 'ProgramCr' },
        { name: 'BeforeDeleteProgramCr' },
        { name: 'ProgramNum' },
        { name: 'DateEndBuilder' },
        { name: 'DateStartWork' },
        { name: 'DateEndWork' },
        { name: 'DateStopWorkGji' },
        { name: 'DateCancelReg' },
        { name: 'AllowReneg' },
        { name: 'Iscluttered' },
        { name: 'HasVidecam' },
        { name: 'DeadlineMissed', defaultValue: false },
        { name: 'DateAcceptCrGji' },
        { name: 'DateAcceptReg' },
        { name: 'DateGjiReg' },
        { name: 'SumDevolopmentPsd' },
        { name: 'SumSmr' },
        { name: 'Address' },
        { name: 'SumSmrApproved' },
        { name: 'SumTehInspection' },
        { name: 'FederalNumber' },
        { name: 'GjiNum' },
        { name: 'RealityObjName' },
        { name: 'ProgramCrName' },
        { name: 'Municipality' },
        { name: 'Description' },
        { name: 'State', defaultValue: null },
        { name: 'MonitoringSmrState', defaultValue: null },
        { name: 'SumAll' },
        { name: 'SumSmrByType' },
        { name: 'SumPsd' },
        { name: 'SumTech' },
        { name: 'Settlement' },
        { name: 'MaxKpkrAmount' },
        { name: 'FactAmountSpent' },
        { name: 'FactStartDate' },
        { name: 'FactEndDate' },
        { name: 'WarrantyEndDate' },
        { name: 'PeriodName' },
        { name: 'MethodFormFund' }
    ]
});