Ext.define('B4.model.RealityObjectDecisionProtocol', {
    extend: 'B4.base.Model',
    //idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'RealityObjectDecisionProtocol'
    },
    fields: [
        { name: 'Id' },
        { name: 'RealityObject' },
        { name: 'File' },
        { name: 'DocumentName' },
        { name: 'DocumentNum' },
        { name: 'DateStart' },
        { name: 'ProtocolDate' },
        { name: 'Description' },
        { name: 'VotesTotalCount' },
        { name: 'VotesParticipatedCount' },
        { name: 'ParticipatedShare' },
        { name: 'HasQuorum' },
        { name: 'PositiveVotesCount' },
        { name: 'DecidedShare' },
        { name: 'AuthorizedPerson' },
        { name: 'PhoneAuthorizedPerson' },
        { name: 'ManOrgName' },
        { name: 'State' },
        { name: 'LetterNumber' },
        { name: 'LetterDate' },
        { name: 'FormVoting' },
        { name: 'EndDateDecision' },
        { name: 'PlaceDecision' },
        { name: 'PlaceMeeting' },
        { name: 'DateMeeting' },
        { name: 'TimeMeeting' },
        { name: 'VotingStartDate' },
        { name: 'VotingStartTime' },
        { name: 'VotingEndDate' },
        { name: 'VotingEndTime' },
        { name: 'OrderTakingDecisionOwners' },
        { name: 'OrderAcquaintanceInfo' },
        { name: 'AnnuaLMeeting' },
        { name: 'LegalityMeeting' },
        { name: 'VotingStatus' }
    ]
});