Ext.define('B4.model.tatarstanprotocolgji.TatarstanProtocolGji', {
    extend: 'B4.model.DocumentGji',
    idProperty: 'Id',
    proxy: {
        type: 'b4proxy',
        controllerName: 'TatarstanProtocolGjiContragent'
    },
    fields: [
        { name: 'Id', useNull: true },
        { name: 'State', defaultValue: null },
        { name: 'Municipality' },
        { name: 'ZonalInspection' },
        { name: 'Executant' },
        { name: 'DateSupply' },
        { name: 'DateOffense' },
        { name: 'TimeOffense' },
        { name: 'Pattern' },
        { name: 'GisUin' },
        { name: 'AnnulReason' },
        { name: 'UpdateReason' },
        { name: 'Sanction' },
        { name: 'Paided', defaultValue: 30 },
        { name: 'PenaltyAmount' },
        { name: 'DateTransferSsp' },
        { name: 'TerminationBasement', defaultValue: 0 },
        { name: 'TerminationDocumentNum' },
        { name: 'SurName' },
        { name: 'Name' },
        { name: 'Patronymic' },
        { name: 'BirthDate' },
        { name: 'BirthPlace' },
        { name: 'Address' },
        { name: 'MaritalStatus' },
        { name: 'DependentCount' },
        { name: 'CitizenshipType', defaultValue: 10 },
        { name: 'Citizenship' },
        { name: 'IdentityDocumentType' },
        { name: 'SerialAndNumberDocument' },
        { name: 'IssueDate' },
        { name: 'IssuingAuthority' },
        { name: 'Company' },
        { name: 'RegistrationAddress' },
        { name: 'Salary' },
        { name: 'ResponsibilityPunishment', defaultValue: false },
        { name: 'Contragent' },
        { name: 'DelegateFio' },
        { name: 'DelegateCompany' },
        { name: 'ProcurationNumber' },
        { name: 'ProcurationDate' },
        { name: 'DelegateResponsibilityPunishment', defaultValue: false },
        { name: 'ProtocolExplanation' },
        { name: 'IsInTribunal', defaultValue: false },
        { name: 'TribunalName' },
        { name: 'OffenseAddress' },
        { name: 'AccusedExplanation' },
        { name: 'RejectionSignature', defaultValue: false },
        { name: 'ResidencePetition', defaultValue: false },
        { name: 'DocumentNumber' },
        { name: 'DocumentDate' },
        { name: 'DocumentYear' },
        { name: 'InspectionId', defaultValue: null },
        { name: 'TypeBase', defaultValue: 140 },
        { name: 'TypeDocumentGji', defaultValue: 160 },
    //контрагент
        { name: 'Ogrn' },
        { name: 'Inn' },
        { name: 'Kpp' },
        { name: 'SettlementAccount' },
        { name: 'BankName' },
        { name: 'CorrAccount' },
        { name: 'Bik' },
        { name: 'Okpo' },
        { name: 'Okonh' },
        { name: 'Okved' },
    //отображение в гриде
        { name: 'Inspectors' },
        { name: 'MunicipalityName' },
        { name: 'Fio' },
    ]
});